## To use SQL in Jupyter notebooks install the following packages.

In [1]:
!pip install ipython-sql

Requirement already satisfied: ipython-sql in c:\users\ashhar\anaconda3\lib\site-packages (0.5.0)
Requirement already satisfied: six in c:\users\ashhar\anaconda3\lib\site-packages (from ipython-sql) (1.16.0)
Requirement already satisfied: sqlalchemy>=2.0 in c:\users\ashhar\anaconda3\lib\site-packages (from ipython-sql) (2.0.6)
Requirement already satisfied: ipython in c:\users\ashhar\anaconda3\lib\site-packages (from ipython-sql) (7.31.1)
Requirement already satisfied: ipython-genutils in c:\users\ashhar\anaconda3\lib\site-packages (from ipython-sql) (0.2.0)
Requirement already satisfied: prettytable in c:\users\ashhar\anaconda3\lib\site-packages (from ipython-sql) (3.6.0)
Requirement already satisfied: sqlparse in c:\users\ashhar\anaconda3\lib\site-packages (from ipython-sql) (0.4.3)
Requirement already satisfied: typing-extensions>=4.2.0 in c:\users\ashhar\anaconda3\lib\site-packages (from sqlalchemy>=2.0->ipython-sql) (4.3.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\ashhar\anaconda3\lib\site-packages (from sqlalchemy>=2.0->ipython-sql) (1.1.1)
Requirement already satisfied: colorama in c:\users\ashhar\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.4.5)
Requirement already satisfied: matplotlib-inline in c:\users\ashhar\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.1.6)
Requirement already satisfied: pygments in c:\users\ashhar\anaconda3\lib\site-packages (from ipython->ipython-sql) (2.11.2)
Requirement already satisfied: traitlets>=4.2 in c:\users\ashhar\anaconda3\lib\site-packages (from ipython->ipython-sql) (5.1.1)
Requirement already satisfied: setuptools>=18.5 in c:\users\ashhar\anaconda3\lib\site-packages (from ipython->ipython-sql) (63.4.1)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in c:\users\ashhar\anaconda3\lib\site-packages (from ipython->ipython-sql) (3.0.20)
Requirement already satisfied: backcall in c:\users\ashhar\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.2.0)
Requirement already satisfied: decorator in c:\users\ashhar\anaconda3\lib\site-packages (from ipython->ipython-sql) (5.1.1)
Requirement already satisfied: jedi>=0.16 in c:\users\ashhar\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.18.1)
Requirement already satisfied: pickleshare in c:\users\ashhar\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.7.5)
Requirement already satisfied: wcwidth in c:\users\ashhar\anaconda3\lib\site-packages (from prettytable->ipython-sql) (0.2.5)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in c:\users\ashhar\anaconda3\lib\site-packages (from jedi>=0.16->ipython->ipython-sql) (0.8.3)

In [2]:
import sqlalchemy

In [3]:
sqlalchemy.create_engine('postgresql://postgres:postgres@localhost/Covidanalysis')

Engine(postgresql://postgres:***@localhost/Covidanalysis)

In [4]:
%load_ext sql

In [5]:
%sql postgresql://postgres:postgres@localhost/Covidanalysis

#### Name of database: Covidanalysis
#### Number of tables : 1
#### Table name: covid_deaths

#### To get to know the overview of the covid_deaths table

In [6]:
%%sql
select * from covid_deaths limit 5

 * postgresql://postgres:***@localhost/Covidanalysis
5 rows affected.

[('AFG', 'Asia', 'Afghanistan', datetime.date(2020, 1, 3), 41128772, None, 0, None, None, 0, None, None, 0.0, None, None, 0.0, None, None, None, None, None, None, None, None, None, None),
 ('AFG', 'Asia', 'Afghanistan', datetime.date(2020, 1, 4), 41128772, None, 0, None, None, 0, None, None, 0.0, None, None, 0.0, None, None, None, None, None, None, None, None, None, None),
 ('AFG', 'Asia', 'Afghanistan', datetime.date(2020, 1, 5), 41128772, None, 0, None, None, 0, None, None, 0.0, None, None, 0.0, None, None, None, None, None, None, None, None, None, None),
 ('AFG', 'Asia', 'Afghanistan', datetime.date(2020, 1, 6), 41128772, None, 0, None, None, 0, None, None, 0.0, None, None, 0.0, None, None, None, None, None, None, None, None, None, None),
 ('AFG', 'Asia', 'Afghanistan', datetime.date(2020, 1, 7), 41128772, None, 0, None, None, 0, None, None, 0.0, None, None, 0.0, None, None, None, None, None, None, None, None, None, None)]

#### convert the above result into dataframe.

In [7]:
result = %sql select * from covid_deaths

 * postgresql://postgres:***@localhost/Covidanalysis
293701 rows affected.

In [8]:
covid_deaths_df = result.DataFrame()

In [9]:
covid_deaths_df

,iso_code,continent,location,date,population,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,...,new_deaths_smoothed_per_million,reproduction_rate,icu_patients,icu_patients_per_million,hosp_patients,hosp_patients_per_million,weekly_icu_admissions,weekly_icu_admissions_per_million,weekly_hosp_admissions,weekly_hosp_admissions_per_million
0,AFG,Asia,Afghanistan,2020-01-03,41128772,NaN,0.0,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AFG,Asia,Afghanistan,2020-01-04,41128772,NaN,0.0,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AFG,Asia,Afghanistan,2020-01-05,41128772,NaN,0.0,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AFG,Asia,Afghanistan,2020-01-06,41128772,NaN,0.0,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AFG,Asia,Afghanistan,2020-01-07,41128772,NaN,0.0,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
293696,ZWE,Africa,Zimbabwe,2023-03-03,16320539,264127.0,0.0,11.571,5668.0,0.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
293697,ZWE,Africa,Zimbabwe,2023-03-04,16320539,264127.0,0.0,4.571,5668.0,0.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
293698,ZWE,Africa,Zimbabwe,2023-03-05,16320539,264127.0,0.0,2.714,5668.0,0.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
293699,ZWE,Africa,Zimbabwe,2023-03-06,16320539,264127.0,0.0,0.000,5668.0,0.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
293700,ZWE,Africa,Zimbabwe,2023-03-07,16320539,264127.0,0.0,0.000,5668.0,0.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

#### Now we will start quering our datasets.

#### Ques 1: Find out date, location, total cases, total deaths in india

In [10]:
%sql select location, date, total_cases, total_deaths from covid_deaths where location='India'

 * postgresql://postgres:***@localhost/Covidanalysis
1166 rows affected.

[('India', datetime.date(2020, 1, 20), None, None),
 ('India', datetime.date(2020, 1, 3), None, None),
 ('India', datetime.date(2020, 1, 4), None, None),
 ('India', datetime.date(2020, 1, 5), None, None),
 ('India', datetime.date(2020, 1, 6), None, None),
 ('India', datetime.date(2020, 1, 7), None, None),
 ('India', datetime.date(2020, 1, 8), None, None),
 ('India', datetime.date(2020, 1, 9), None, None),
 ('India', datetime.date(2020, 1, 10), None, None),
 ('India', datetime.date(2020, 1, 11), None, None),
 ('India', datetime.date(2020, 1, 12), None, None),
 ('India', datetime.date(2020, 1, 13), None, None),
 ('India', datetime.date(2020, 1, 14), None, None),
 ('India', datetime.date(2020, 1, 15), None, None),
 ('India', datetime.date(2020, 1, 16), None, None),
 ('India', datetime.date(2020, 1, 17), None, None),
 ('India', datetime.date(2020, 1, 18), None, None),
 ('India', datetime.date(2020, 1, 19), None, None),
 ('India', datetime.date(2020, 1, 21), None, None),
 ('India', datetime.date(2020, 1, 22), None, None),
 ('India', datetime.date(2020, 1, 23), None, None),
 ('India', datetime.date(2020, 1, 24), None, None),
 ('India', datetime.date(2020, 1, 25), None, None),
 ('India', datetime.date(2020, 1, 26), None, None),
 ('India', datetime.date(2020, 1, 27), None, None),
 ('India', datetime.date(2020, 1, 28), None, None),
 ('India', datetime.date(2020, 1, 29), None, None),
 ('India', datetime.date(2020, 1, 30), 1.0, None),
 ('India', datetime.date(2020, 1, 31), 5.0, None),
 ('India', datetime.date(2020, 2, 1), 5.0, None),
 ('India', datetime.date(2020, 2, 2), 2.0, None),
 ('India', datetime.date(2020, 2, 3), 3.0, None),
 ('India', datetime.date(2020, 2, 4), 7.0, None),
 ('India', datetime.date(2020, 2, 5), 7.0, None),
 ('India', datetime.date(2020, 2, 6), 7.0, None),
 ('India', datetime.date(2020, 2, 7), 7.0, None),
 ('India', datetime.date(2020, 2, 8), 7.0, None),
 ('India', datetime.date(2020, 2, 9), 7.0, None),
 ('India', datetime.date(2020, 2, 10), 7.0, None),
 ('India', datetime.date(2020, 2, 11), 7.0, None),
 ('India', datetime.date(2020, 2, 12), 7.0, None),
 ('India', datetime.date(2020, 2, 13), 7.0, None),
 ('India', datetime.date(2020, 2, 14), 7.0, None),
 ('India', datetime.date(2020, 2, 15), 7.0, None),
 ('India', datetime.date(2020, 2, 16), 7.0, None),
 ('India', datetime.date(2020, 2, 17), 7.0, None),
 ('India', datetime.date(2020, 2, 18), 7.0, None),
 ('India', datetime.date(2020, 2, 19), 7.0, None),
 ('India', datetime.date(2020, 2, 20), 7.0, None),
 ('India', datetime.date(2020, 2, 21), 7.0, None),
 ('India', datetime.date(2020, 2, 22), 7.0, None),
 ('India', datetime.date(2020, 2, 23), 7.0, None),
 ('India', datetime.date(2020, 2, 24), 7.0, None),
 ('India', datetime.date(2020, 2, 25), 7.0, None),
 ('India', datetime.date(2020, 2, 26), 7.0, None),
 ('India', datetime.date(2020, 2, 27), 7.0, None),
 ('India', datetime.date(2020, 2, 28), 7.0, None),
 ('India', datetime.date(2020, 2, 29), 7.0, None),
 ('India', datetime.date(2020, 3, 1), 7.0, None),
 ('India', datetime.date(2020, 3, 2), 5.0, None),
 ('India', datetime.date(2020, 3, 3), 9.0, None),
 ('India', datetime.date(2020, 3, 4), 28.0, None),
 ('India', datetime.date(2020, 3, 5), 29.0, None),
 ('India', datetime.date(2020, 3, 6), 31.0, None),
 ('India', datetime.date(2020, 3, 7), 34.0, None),
 ('India', datetime.date(2020, 3, 8), 39.0, None),
 ('India', datetime.date(2020, 3, 9), 44.0, None),
 ('India', datetime.date(2020, 3, 10), 50.0, None),
 ('India', datetime.date(2020, 3, 11), 60.0, None),
 ('India', datetime.date(2020, 3, 12), 73.0, None),
 ('India', datetime.date(2020, 3, 13), 81.0, 1.0),
 ('India', datetime.date(2020, 3, 14), 84.0, 2.0),
 ('India', datetime.date(2020, 3, 15), 107.0, 2.0),
 ('India', datetime.date(2020, 3, 16), 114.0, 2.0),
 ('India', datetime.date(2020, 3, 17), 137.0, 3.0),
 ('India', datetime.date(2020, 3, 18), 151.0, 3.0),
 ('India', datetime.date(2020, 3, 19), 173.0, 4.0),
 ('India', datetime.date(2020, 3, 20), 223.0, 4.0),
 ('India', datetime.date(2020, 3, 21), 283.0, 4.0),
 ('India', datetime.date(2020, 3, 22), 360.0, 7.0),
 ('India', datetime.date(2020, 3, 23), 434.0, 9.0),
 ('India', datetime.date(2020, 3, 24), 519.0, 9.0),
 ('India', datetime.date(2020, 3, 25), 606.0, 10.0),
 ('India', datetime.date(2020, 3, 26), 649.0, 13.0),
 ('India', datetime.date(2020, 3, 27), 724.0, 17.0),
 ('India', datetime.date(2020, 3, 28), 909.0, 19.0),
 ('India', datetime.date(2020, 3, 29), 979.0, 25.0),
 ('India', datetime.date(2020, 3, 30), 1071.0, 29.0),
 ('India', datetime.date(2020, 3, 31), 1251.0, 32.0),
 ('India', datetime.date(2020, 4, 1), 1637.0, 38.0),
 ('India', datetime.date(2020, 4, 2), 1965.0, 50.0),
 ('India', datetime.date(2020, 4, 3), 2301.0, 56.0),
 ('India', datetime.date(2020, 4, 4), 2902.0, 68.0),
 ('India', datetime.date(2020, 4, 5), 3374.0, 77.0),
 ('India', datetime.date(2020, 4, 6), 4067.0, 109.0),
 ('India', datetime.date(2020, 4, 7), 4421.0, 114.0),
 ('India', datetime.date(2020, 4, 8), 5274.0, 149.0),
 ('India', datetime.date(2020, 4, 9), 5865.0, 169.0),
 ('India', datetime.date(2020, 4, 10), 6412.0, 199.0),
 ('India', datetime.date(2020, 4, 11), 7447.0, 239.0),
 ('India', datetime.date(2020, 4, 12), 8356.0, 273.0),
 ('India', datetime.date(2020, 4, 13), 9152.0, 308.0),
 ('India', datetime.date(2020, 4, 14), 10363.0, 339.0),
 ('India', datetime.date(2020, 4, 15), 11439.0, 377.0),
 ('India', datetime.date(2020, 4, 16), 12380.0, 414.0),
 ('India', datetime.date(2020, 4, 17), 13387.0, 437.0),
 ('India', datetime.date(2020, 4, 18), 14378.0, 480.0),
 ('India', datetime.date(2020, 4, 19), 15712.0, 507.0),
 ('India', datetime.date(2020, 4, 20), 17265.0, 543.0),
 ('India', datetime.date(2020, 4, 21), 18601.0, 590.0),
 ('India', datetime.date(2020, 4, 22), 19984.0, 640.0),
 ('India', datetime.date(2020, 4, 23), 21393.0, 681.0),
 ('India', datetime.date(2020, 4, 24), 23077.0, 718.0),
 ('India', datetime.date(2020, 4, 25), 24506.0, 775.0),
 ('India', datetime.date(2020, 4, 26), 26496.0, 824.0),
 ('India', datetime.date(2020, 4, 27), 27892.0, 872.0),
 ('India', datetime.date(2020, 4, 28), 29435.0, 934.0),
 ('India', datetime.date(2020, 4, 29), 31332.0, 1007.0),
 ('India', datetime.date(2020, 4, 30), 33050.0, 1074.0),
 ('India', datetime.date(2020, 5, 1), 35043.0, 1147.0),
 ('India', datetime.date(2020, 5, 2), 37336.0, 1218.0),
 ('India', datetime.date(2020, 5, 3), 39980.0, 1301.0),
 ('India', datetime.date(2020, 5, 4), 42533.0, 1373.0),
 ('India', datetime.date(2020, 5, 5), 46433.0, 1568.0),
 ('India', datetime.date(2020, 5, 6), 49391.0, 1694.0),
 ('India', datetime.date(2020, 5, 7), 52952.0, 1783.0),
 ('India', datetime.date(2020, 5, 8), 56342.0, 1886.0),
 ('India', datetime.date(2020, 5, 9), 59662.0, 1981.0),
 ('India', datetime.date(2020, 5, 10), 62939.0, 2109.0),
 ('India', datetime.date(2020, 5, 11), 67152.0, 2206.0),
 ('India', datetime.date(2020, 5, 12), 70756.0, 2293.0),
 ('India', datetime.date(2020, 5, 13), 74281.0, 2415.0),
 ('India', datetime.date(2020, 5, 14), 78003.0, 2549.0),
 ('India', datetime.date(2020, 5, 15), 81970.0, 2649.0),
 ('India', datetime.date(2020, 5, 16), 85940.0, 2752.0),
 ('India', datetime.date(2020, 5, 17), 90927.0, 2872.0),
 ('India', datetime.date(2020, 5, 18), 96169.0, 3029.0),
 ('India', datetime.date(2020, 5, 19), 101139.0, 3163.0),
 ('India', datetime.date(2020, 5, 20), 106750.0, 3303.0),
 ('India', datetime.date(2020, 5, 21), 112359.0, 3435.0),
 ('India', datetime.date(2020, 5, 22), 118447.0, 3583.0),
 ('India', datetime.date(2020, 5, 23), 125101.0, 3720.0),
 ('India', datetime.date(2020, 5, 24), 131868.0, 3867.0),
 ('India', datetime.date(2020, 5, 25), 138845.0, 4021.0),
 ('India', datetime.date(2020, 5, 26), 145380.0, 4167.0),
 ('India', datetime.date(2020, 5, 27), 151767.0, 4337.0),
 ('India', datetime.date(2020, 5, 28), 158333.0, 4531.0),
 ('India', datetime.date(2020, 5, 29), 165799.0, 4706.0),
 ('India', datetime.date(2020, 5, 30), 173763.0, 4971.0),
 ('India', datetime.date(2020, 5, 31), 182143.0, 5164.0),
 ('India', datetime.date(2020, 6, 1), 190535.0, 5394.0),
 ('India', datetime.date(2020, 6, 2), 198706.0, 5598.0),
 ('India', datetime.date(2020, 6, 3), 207615.0, 5815.0),
 ('India', datetime.date(2020, 6, 4), 216919.0, 6075.0),
 ('India', datetime.date(2020, 6, 5), 226770.0, 6348.0),
 ('India', datetime.date(2020, 6, 6), 236657.0, 6642.0),
 ('India', datetime.date(2020, 6, 7), 246628.0, 6929.0),
 ('India', datetime.date(2020, 6, 8), 256611.0, 7200.0),
 ('India', datetime.date(2020, 6, 9), 266598.0, 7471.0),
 ('India', datetime.date(2020, 6, 10), 276583.0, 7745.0),
 ('India', datetime.date(2020, 6, 11), 286579.0, 8102.0),
 ('India', datetime.date(2020, 6, 12), 297535.0, 8498.0),
 ('India', datetime.date(2020, 6, 13), 308993.0, 8884.0),
 ('India', datetime.date(2020, 6, 14), 320922.0, 9195.0),
 ('India', datetime.date(2020, 6, 15), 332424.0, 9520.0),
 ('India', datetime.date(2020, 6, 16), 343091.0, 9900.0),
 ('India', datetime.date(2020, 6, 17), 354065.0, 11903.0),
 ('India', datetime.date(2020, 6, 18), 366946.0, 12237.0),
 ('India', datetime.date(2020, 6, 19), 380532.0, 12573.0),
 ('India', datetime.date(2020, 6, 20), 395048.0, 12948.0),
 ('India', datetime.date(2020, 6, 21), 410461.0, 13254.0),
 ('India', datetime.date(2020, 6, 22), 425282.0, 13699.0),
 ('India', datetime.date(2020, 6, 23), 440215.0, 14011.0),
 ('India', datetime.date(2020, 6, 24), 456183.0, 14476.0),
 ('India', datetime.date(2020, 6, 25), 473105.0, 14894.0),
 ('India', datetime.date(2020, 6, 26), 490401.0, 15301.0),
 ('India', datetime.date(2020, 6, 27), 508953.0, 15685.0),
 ('India', datetime.date(2020, 6, 28), 528859.0, 16095.0),
 ('India', datetime.date(2020, 6, 29), 548318.0, 16475.0),
 ('India', datetime.date(2020, 6, 30), 566840.0, 16893.0),
 ('India', datetime.date(2020, 7, 1), 585493.0, 17400.0),
 ('India', datetime.date(2020, 7, 2), 604641.0, 17834.0),
 ('India', datetime.date(2020, 7, 3), 625544.0, 18213.0),
 ('India', datetime.date(2020, 7, 4), 648315.0, 18655.0),
 ('India', datetime.date(2020, 7, 5), 673165.0, 19268.0),
 ('India', datetime.date(2020, 7, 6), 697413.0, 19693.0),
 ('India', datetime.date(2020, 7, 7), 719665.0, 20160.0),
 ('India', datetime.date(2020, 7, 8), 742417.0, 20642.0),
 ('India', datetime.date(2020, 7, 9), 767296.0, 21129.0),
 ('India', datetime.date(2020, 7, 10), 793802.0, 21604.0),
 ('India', datetime.date(2020, 7, 11), 820916.0, 22123.0),
 ('India', datetime.date(2020, 7, 12), 849553.0, 22674.0),
 ('India', datetime.date(2020, 7, 13), 878254.0, 23174.0),
 ('India', datetime.date(2020, 7, 14), 906752.0, 23727.0),
 ('India', datetime.date(2020, 7, 15), 936181.0, 24309.0),
 ('India', datetime.date(2020, 7, 16), 968876.0, 24915.0),
 ('India', datetime.date(2020, 7, 17), 1003832.0, 25602.0),
 ('India', datetime.date(2020, 7, 18), 1038716.0, 26273.0),
 ('India', datetime.date(2020, 7, 19), 1077618.0, 26816.0),
 ('India', datetime.date(2020, 7, 20), 1118043.0, 27497.0),
 ('India', datetime.date(2020, 7, 21), 1155191.0, 28084.0),
 ('India', datetime.date(2020, 7, 22), 1192915.0, 28732.0),
 ('India', datetime.date(2020, 7, 23), 1238635.0, 29861.0),
 ('India', datetime.date(2020, 7, 24), 1287945.0, 30601.0),
 ('India', datetime.date(2020, 7, 25), 1336861.0, 31358.0),
 ('India', datetime.date(2020, 7, 26), 1385522.0, 32063.0),
 ('India', datetime.date(2020, 7, 27), 1435453.0, 32771.0),
 ('India', datetime.date(2020, 7, 28), 1483156.0, 33425.0),
 ('India', datetime.date(2020, 7, 29), 1531669.0, 34193.0),
 ('India', datetime.date(2020, 7, 30), 1583792.0, 34968.0),
 ('India', datetime.date(2020, 7, 31), 1638870.0, 35747.0),
 ('India', datetime.date(2020, 8, 1), 1695988.0, 36511.0),
 ('India', datetime.date(2020, 8, 2), 1750723.0, 37364.0),
 ('India', datetime.date(2020, 8, 3), 1803695.0, 38135.0),
 ('India', datetime.date(2020, 8, 4), 1855745.0, 38938.0),
 ('India', datetime.date(2020, 8, 5), 1908254.0, 39795.0),
 ('India', datetime.date(2020, 8, 6), 1964536.0, 40699.0),
 ('India', datetime.date(2020, 8, 7), 2027074.0, 41585.0),
 ('India', datetime.date(2020, 8, 8), 2088611.0, 42518.0),
 ('India', datetime.date(2020, 8, 9), 2153010.0, 43379.0),
 ('India', datetime.date(2020, 8, 10), 2215074.0, 44386.0),
 ('India', datetime.date(2020, 8, 11), 2268675.0, 45257.0),
 ('India', datetime.date(2020, 8, 12), 2329638.0, 46091.0),
 ('India', datetime.date(2020, 8, 13), 2396637.0, 47033.0),
 ('India', datetime.date(2020, 8, 14), 2461190.0, 48040.0),
 ('India', datetime.date(2020, 8, 15), 2526192.0, 49036.0),
 ('India', datetime.date(2020, 8, 16), 2589682.0, 49980.0),
 ('India', datetime.date(2020, 8, 17), 2647663.0, 50921.0),
 ('India', datetime.date(2020, 8, 18), 2702742.0, 51797.0),
 ('India', datetime.date(2020, 8, 19), 2767273.0, 52889.0),
 ('India', datetime.date(2020, 8, 20), 2836925.0, 53866.0),
 ('India', datetime.date(2020, 8, 21), 2905823.0, 54849.0),
 ('India', datetime.date(2020, 8, 22), 2975701.0, 55794.0),
 ('India', datetime.date(2020, 8, 23), 3044940.0, 56706.0),
 ('India', datetime.date(2020, 8, 24), 3106348.0, 57542.0),
 ('India', datetime.date(2020, 8, 25), 3167323.0, 58390.0),
 ('India', datetime.date(2020, 8, 26), 3234474.0, 59449.0),
 ('India', datetime.date(2020, 8, 27), 3310234.0, 60472.0),
 ('India', datetime.date(2020, 8, 28), 3387500.0, 61529.0),
 ('India', datetime.date(2020, 8, 29), 3463972.0, 62550.0),
 ('India', datetime.date(2020, 8, 30), 3542733.0, 63498.0),
 ('India', datetime.date(2020, 8, 31), 3621245.0, 64469.0),
 ('India', datetime.date(2020, 9, 1), 3691166.0, 65288.0),
 ('India', datetime.date(2020, 9, 2), 3769523.0, 66333.0),
 ('India', datetime.date(2020, 9, 3), 3853406.0, 67376.0),
 ('India', datetime.date(2020, 9, 4), 3936747.0, 68472.0),
 ('India', datetime.date(2020, 9, 5), 4023179.0, 69561.0),
 ('India', datetime.date(2020, 9, 6), 4113811.0, 70626.0),
 ('India', datetime.date(2020, 9, 7), 4204613.0, 71642.0),
 ('India', datetime.date(2020, 9, 8), 4280422.0, 72775.0),
 ('India', datetime.date(2020, 9, 9), 4370128.0, 73890.0),
 ('India', datetime.date(2020, 9, 10), 4465863.0, 75062.0),
 ('India', datetime.date(2020, 9, 11), 4562414.0, 76271.0),
 ('India', datetime.date(2020, 9, 12), 4659984.0, 77472.0),
 ('India', datetime.date(2020, 9, 13), 4754356.0, 78586.0),
 ('India', datetime.date(2020, 9, 14), 4846427.0, 79722.0),
 ('India', datetime.date(2020, 9, 15), 4930236.0, 80776.0),
 ('India', datetime.date(2020, 9, 16), 5020359.0, 82066.0),
 ('India', datetime.date(2020, 9, 17), 5118253.0, 83198.0),
 ('India', datetime.date(2020, 9, 18), 5214677.0, 84372.0),
 ('India', datetime.date(2020, 9, 19), 5308014.0, 85619.0),
 ('India', datetime.date(2020, 9, 20), 5400619.0, 86752.0),
 ('India', datetime.date(2020, 9, 21), 5487580.0, 87882.0),
 ('India', datetime.date(2020, 9, 22), 5562663.0, 88935.0),
 ('India', datetime.date(2020, 9, 23), 5646010.0, 90020.0),
 ('India', datetime.date(2020, 9, 24), 5732518.0, 91149.0),
 ('India', datetime.date(2020, 9, 25), 5818570.0, 92290.0),
 ('India', datetime.date(2020, 9, 26), 5903932.0, 93379.0),
 ('India', datetime.date(2020, 9, 27), 5992532.0, 94503.0),
 ('India', datetime.date(2020, 9, 28), 6074702.0, 95542.0),
 ('India', datetime.date(2020, 9, 29), 6145291.0, 96318.0),
 ('India', datetime.date(2020, 9, 30), 6225763.0, 97497.0),
 ('India', datetime.date(2020, 10, 1), 6312584.0, 98678.0),
 ('India', datetime.date(2020, 10, 2), 6394068.0, 99773.0),
 ('India', datetime.date(2020, 10, 3), 6473544.0, 100842.0),
 ('India', datetime.date(2020, 10, 4), 6549373.0, 101782.0),
 ('India', datetime.date(2020, 10, 5), 6623815.0, 102685.0),
 ('India', datetime.date(2020, 10, 6), 6685082.0, 103569.0),
 ('India', datetime.date(2020, 10, 7), 6757131.0, 104555.0),
 ('India', datetime.date(2020, 10, 8), 6835655.0, 105526.0),
 ('India', datetime.date(2020, 10, 9), 6906151.0, 106490.0),
 ('India', datetime.date(2020, 10, 10), 6979423.0, 107416.0),
 ('India', datetime.date(2020, 10, 11), 7053806.0, 108334.0),
 ('India', datetime.date(2020, 10, 12), 7120538.0, 109150.0),
 ('India', datetime.date(2020, 10, 13), 7175880.0, 109856.0),
 ('India', datetime.date(2020, 10, 14), 7239389.0, 110586.0),
 ('India', datetime.date(2020, 10, 15), 7307097.0, 111266.0),
 ('India', datetime.date(2020, 10, 16), 7370468.0, 112161.0),
 ('India', datetime.date(2020, 10, 17), 7432680.0, 112998.0),
 ('India', datetime.date(2020, 10, 18), 7494551.0, 114031.0),
 ('India', datetime.date(2020, 10, 19), 7550273.0, 114610.0),
 ('India', datetime.date(2020, 10, 20), 7597063.0, 115197.0),
 ('India', datetime.date(2020, 10, 21), 7651107.0, 115914.0),
 ('India', datetime.date(2020, 10, 22), 7706946.0, 116616.0),
 ('India', datetime.date(2020, 10, 23), 7761312.0, 117306.0),
 ('India', datetime.date(2020, 10, 24), 7814682.0, 117956.0),
 ('India', datetime.date(2020, 10, 25), 7864811.0, 118534.0),
 ('India', datetime.date(2020, 10, 26), 7909959.0, 119014.0),
 ('India', datetime.date(2020, 10, 27), 7946429.0, 119502.0),
 ('India', datetime.date(2020, 10, 28), 7990322.0, 120010.0),
 ('India', datetime.date(2020, 10, 29), 8040203.0, 120527.0),
 ('India', datetime.date(2020, 10, 30), 8088851.0, 121090.0),
 ('India', datetime.date(2020, 10, 31), 8137119.0, 121641.0),
 ('India', datetime.date(2020, 11, 1), 8184082.0, 122111.0),
 ('India', datetime.date(2020, 11, 2), 8229313.0, 122607.0),
 ('India', datetime.date(2020, 11, 3), 8267623.0, 123097.0),
 ('India', datetime.date(2020, 11, 4), 8313876.0, 123611.0),
 ('India', datetime.date(2020, 11, 5), 8364086.0, 124315.0),
 ('India', datetime.date(2020, 11, 6), 8411724.0, 124985.0),
 ('India', datetime.date(2020, 11, 7), 8462080.0, 125562.0),
 ('India', datetime.date(2020, 11, 8), 8507754.0, 126121.0),
 ('India', datetime.date(2020, 11, 9), 8553657.0, 126611.0),
 ('India', datetime.date(2020, 11, 10), 8591730.0, 127059.0),
 ('India', datetime.date(2020, 11, 11), 8636011.0, 127571.0),
 ('India', datetime.date(2020, 11, 12), 8683916.0, 128121.0),
 ('India', datetime.date(2020, 11, 13), 8728795.0, 128668.0),
 ('India', datetime.date(2020, 11, 14), 8773479.0, 129188.0),
 ('India', datetime.date(2020, 11, 15), 8814579.0, 129635.0),
 ('India', datetime.date(2020, 11, 16), 8845127.0, 130070.0),
 ('India', datetime.date(2020, 11, 17), 8874290.0, 130519.0),
 ('India', datetime.date(2020, 11, 18), 8912907.0, 130993.0),
 ('India', datetime.date(2020, 11, 19), 8958483.0, 131578.0),
 ('India', datetime.date(2020, 11, 20), 9004365.0, 132162.0),
 ('India', datetime.date(2020, 11, 21), 9050597.0, 132726.0),
 ('India', datetime.date(2020, 11, 22), 9095806.0, 133227.0),
 ('India', datetime.date(2020, 11, 23), 9139865.0, 133738.0),
 ('India', datetime.date(2020, 11, 24), 9177840.0, 134218.0),
 ('India', datetime.date(2020, 11, 25), 9222216.0, 134699.0),
 ('India', datetime.date(2020, 11, 26), 9266705.0, 135223.0),
 ('India', datetime.date(2020, 11, 27), 9309787.0, 135715.0),
 ('India', datetime.date(2020, 11, 28), 9351109.0, 136200.0),
 ('India', datetime.date(2020, 11, 29), 9392919.0, 136696.0),
 ('India', datetime.date(2020, 11, 30), 9431691.0, 137139.0),
 ('India', datetime.date(2020, 12, 1), 9462809.0, 137621.0),
 ('India', datetime.date(2020, 12, 2), 9499413.0, 138122.0),
 ('India', datetime.date(2020, 12, 3), 9534964.0, 138648.0),
 ('India', datetime.date(2020, 12, 4), 9571559.0, 139188.0),
 ('India', datetime.date(2020, 12, 5), 9608211.0, 139700.0),
 ('India', datetime.date(2020, 12, 6), 9644222.0, 140182.0),
 ('India', datetime.date(2020, 12, 7), 9677203.0, 140573.0),
 ('India', datetime.date(2020, 12, 8), 9703770.0, 140958.0),
 ('India', datetime.date(2020, 12, 9), 9735850.0, 141360.0),
 ('India', datetime.date(2020, 12, 10), 9767371.0, 141772.0),
 ('India', datetime.date(2020, 12, 11), 9796769.0, 142186.0),
 ('India', datetime.date(2020, 12, 12), 9826775.0, 142628.0),
 ('India', datetime.date(2020, 12, 13), 9857029.0, 143019.0),
 ('India', datetime.date(2020, 12, 14), 9884100.0, 143355.0),
 ('India', datetime.date(2020, 12, 15), 9906165.0, 143709.0),
 ('India', datetime.date(2020, 12, 16), 9932547.0, 144096.0),

#### Finding out the death percentage on daily basis in India

In [11]:
%sql select location, date, total_cases, total_deaths, ROUND(CAST((total_deaths/total_cases)*100 as numeric), 2)  as death_percent from covid_deaths where location='India' order by death_percent

 * postgresql://postgres:***@localhost/Covidanalysis
1166 rows affected.

[('India', datetime.date(2021, 5, 9), 22296414.0, 242362.0, Decimal('1.09')),
 ('India', datetime.date(2021, 5, 11), 22992517.0, 249992.0, Decimal('1.09')),
 ('India', datetime.date(2021, 5, 10), 22662575.0, 246116.0, Decimal('1.09')),
 ('India', datetime.date(2021, 5, 16), 24684077.0, 270284.0, Decimal('1.09')),
 ('India', datetime.date(2021, 5, 15), 24372907.0, 266207.0, Decimal('1.09')),
 ('India', datetime.date(2021, 5, 14), 24046809.0, 262317.0, Decimal('1.09')),
 ('India', datetime.date(2021, 5, 13), 23703665.0, 258317.0, Decimal('1.09')),
 ('India', datetime.date(2021, 5, 12), 23340938.0, 254197.0, Decimal('1.09')),
 ('India', datetime.date(2021, 5, 5), 20665148.0, 226188.0, Decimal('1.09')),
 ('India', datetime.date(2021, 5, 6), 21077410.0, 230168.0, Decimal('1.09')),
 ('India', datetime.date(2021, 5, 7), 21491598.0, 234083.0, Decimal('1.09')),
 ('India', datetime.date(2021, 5, 8), 21892676.0, 238270.0, Decimal('1.09')),
 ('India', datetime.date(2021, 5, 3), 19925604.0, 218959.0, Decimal('1.10')),
 ('India', datetime.date(2021, 5, 18), 25228996.0, 278719.0, Decimal('1.10')),
 ('India', datetime.date(2021, 5, 17), 24965463.0, 274390.0, Decimal('1.10')),
 ('India', datetime.date(2021, 5, 4), 20282833.0, 222408.0, Decimal('1.10')),
 ('India', datetime.date(2021, 5, 2), 19557457.0, 215542.0, Decimal('1.10')),
 ('India', datetime.date(2021, 4, 30), 18762976.0, 208330.0, Decimal('1.11')),
 ('India', datetime.date(2021, 5, 20), 25772440.0, 287122.0, Decimal('1.11')),
 ('India', datetime.date(2021, 5, 19), 25496330.0, 283248.0, Decimal('1.11')),
 ('India', datetime.date(2021, 4, 29), 18376524.0, 204832.0, Decimal('1.11')),
 ('India', datetime.date(2021, 5, 1), 19164969.0, 211853.0, Decimal('1.11')),
 ('India', datetime.date(2021, 4, 28), 17997267.0, 201187.0, Decimal('1.12')),
 ('India', datetime.date(2021, 5, 22), 26289290.0, 295525.0, Decimal('1.12')),
 ('India', datetime.date(2021, 5, 21), 26031991.0, 291331.0, Decimal('1.12')),
 ('India', datetime.date(2021, 4, 27), 17636307.0, 197894.0, Decimal('1.12')),
 ('India', datetime.date(2021, 5, 23), 26530132.0, 299266.0, Decimal('1.13')),
 ('India', datetime.date(2021, 4, 25), 16960172.0, 192311.0, Decimal('1.13')),
 ('India', datetime.date(2021, 4, 26), 17313163.0, 195123.0, Decimal('1.13')),
 ('India', datetime.date(2021, 5, 25), 26948874.0, 307231.0, Decimal('1.14')),
 ('India', datetime.date(2021, 5, 24), 26752447.0, 303720.0, Decimal('1.14')),
 ('India', datetime.date(2021, 4, 24), 16610481.0, 189544.0, Decimal('1.14')),
 ('India', datetime.date(2021, 4, 23), 16263695.0, 186920.0, Decimal('1.15')),
 ('India', datetime.date(2021, 5, 26), 27157795.0, 311388.0, Decimal('1.15')),
 ('India', datetime.date(2021, 5, 27), 27369093.0, 315235.0, Decimal('1.15')),
 ('India', datetime.date(2021, 4, 22), 15930965.0, 184657.0, Decimal('1.16')),
 ('India', datetime.date(2021, 5, 29), 27729247.0, 322512.0, Decimal('1.16')),
 ('India', datetime.date(2021, 5, 28), 27555457.0, 318895.0, Decimal('1.16')),
 ('India', datetime.date(2021, 5, 30), 27894800.0, 325972.0, Decimal('1.17')),
 ('India', datetime.date(2021, 5, 31), 28047534.0, 329100.0, Decimal('1.17')),
 ('India', datetime.date(2021, 4, 21), 15616130.0, 182553.0, Decimal('1.17')),
 ('India', datetime.date(2022, 10, 26), 44645768.0, 528981.0, Decimal('1.18')),
 ('India', datetime.date(2022, 10, 27), 44646880.0, 528987.0, Decimal('1.18')),
 ('India', datetime.date(2022, 10, 28), 44649088.0, 528999.0, Decimal('1.18')),
 ('India', datetime.date(2022, 10, 29), 44650662.0, 529008.0, Decimal('1.18')),
 ('India', datetime.date(2022, 10, 30), 44652266.0, 529016.0, Decimal('1.18')),
 ('India', datetime.date(2022, 10, 31), 44653592.0, 529024.0, Decimal('1.18')),
 ('India', datetime.date(2022, 11, 1), 44654638.0, 529077.0, Decimal('1.18')),
 ('India', datetime.date(2021, 4, 20), 15321089.0, 180530.0, Decimal('1.18')),
 ('India', datetime.date(2021, 6, 1), 28175044.0, 331895.0, Decimal('1.18')),
 ('India', datetime.date(2021, 6, 2), 28307832.0, 335102.0, Decimal('1.18')),
 ('India', datetime.date(2022, 10, 21), 44638636.0, 528953.0, Decimal('1.18')),
 ('India', datetime.date(2022, 10, 22), 44640748.0, 528957.0, Decimal('1.18')),
 ('India', datetime.date(2022, 10, 23), 44642742.0, 528961.0, Decimal('1.18')),
 ('India', datetime.date(2022, 10, 24), 44644076.0, 528977.0, Decimal('1.18')),
 ('India', datetime.date(2022, 10, 25), 44644938.0, 528980.0, Decimal('1.18')),
 ('India', datetime.date(2022, 12, 4), 44673392.0, 530628.0, Decimal('1.19')),
 ('India', datetime.date(2022, 12, 3), 44673166.0, 530627.0, Decimal('1.19')),
 ('India', datetime.date(2022, 12, 2), 44672913.0, 530624.0, Decimal('1.19')),
 ('India', datetime.date(2022, 12, 1), 44672638.0, 530622.0, Decimal('1.19')),
 ('India', datetime.date(2022, 11, 30), 44672347.0, 530620.0, Decimal('1.19')),
 ('India', datetime.date(2022, 11, 29), 44672068.0, 530615.0, Decimal('1.19')),
 ('India', datetime.date(2022, 11, 28), 44671853.0, 530614.0, Decimal('1.19')),
 ('India', datetime.date(2022, 11, 27), 44671562.0, 530612.0, Decimal('1.19')),
 ('India', datetime.date(2022, 11, 26), 44671219.0, 530608.0, Decimal('1.19')),
 ('India', datetime.date(2022, 11, 25), 44670830.0, 530604.0, Decimal('1.19')),
 ('India', datetime.date(2022, 11, 24), 44670483.0, 530601.0, Decimal('1.19')),
 ('India', datetime.date(2022, 11, 23), 44670075.0, 530596.0, Decimal('1.19')),
 ('India', datetime.date(2022, 11, 22), 44669715.0, 530591.0, Decimal('1.19')),
 ('India', datetime.date(2022, 11, 21), 44669421.0, 530586.0, Decimal('1.19')),
 ('India', datetime.date(2022, 11, 20), 44669015.0, 530574.0, Decimal('1.19')),
 ('India', datetime.date(2022, 11, 19), 44668523.0, 530570.0, Decimal('1.19')),
 ('India', datetime.date(2022, 11, 18), 44667967.0, 530553.0, Decimal('1.19')),
 ('India', datetime.date(2022, 11, 17), 44667311.0, 530546.0, Decimal('1.19')),
 ('India', datetime.date(2022, 11, 16), 44666676.0, 530535.0, Decimal('1.19')),
 ('India', datetime.date(2022, 11, 15), 44666175.0, 530533.0, Decimal('1.19')),
 ('India', datetime.date(2022, 11, 14), 44666924.0, 530532.0, Decimal('1.19')),
 ('India', datetime.date(2022, 11, 13), 44666377.0, 530531.0, Decimal('1.19')),
 ('India', datetime.date(2022, 11, 12), 44665643.0, 530528.0, Decimal('1.19')),
 ('India', datetime.date(2022, 11, 11), 44664810.0, 530520.0, Decimal('1.19')),
 ('India', datetime.date(2022, 11, 10), 44663968.0, 530514.0, Decimal('1.19')),
 ('India', datetime.date(2022, 11, 9), 44662952.0, 530511.0, Decimal('1.19')),
 ('India', datetime.date(2022, 11, 8), 44662141.0, 530509.0, Decimal('1.19')),
 ('India', datetime.date(2022, 11, 7), 44661516.0, 530509.0, Decimal('1.19')),
 ('India', datetime.date(2022, 11, 6), 44660579.0, 530500.0, Decimal('1.19')),
 ('India', datetime.date(2022, 11, 5), 44659447.0, 530486.0, Decimal('1.19')),
 ('India', datetime.date(2022, 11, 4), 44658365.0, 530479.0, Decimal('1.19')),
 ('India', datetime.date(2022, 11, 3), 44657149.0, 530461.0, Decimal('1.19')),
 ('India', datetime.date(2022, 11, 2), 44655828.0, 530452.0, Decimal('1.19')),
 ('India', datetime.date(2022, 10, 20), 44636517.0, 528943.0, Decimal('1.19')),
 ('India', datetime.date(2022, 10, 19), 44634376.0, 528923.0, Decimal('1.19')),
 ('India', datetime.date(2022, 10, 18), 44632430.0, 528913.0, Decimal('1.19')),
 ('India', datetime.date(2022, 10, 17), 44630888.0, 528905.0, Decimal('1.19')),
 ('India', datetime.date(2022, 10, 16), 44628828.0, 528895.0, Decimal('1.19')),
 ('India', datetime.date(2022, 10, 15), 44626427.0, 528874.0, Decimal('1.19')),
 ('India', datetime.date(2022, 10, 14), 44623997.0, 528857.0, Decimal('1.19')),
 ('India', datetime.date(2022, 10, 13), 44621319.0, 528847.0, Decimal('1.19')),
 ('India', datetime.date(2022, 10, 12), 44618533.0, 528835.0, Decimal('1.19')),
 ('India', datetime.date(2022, 10, 11), 44616394.0, 528822.0, Decimal('1.19')),
 ('India', datetime.date(2022, 10, 10), 44614437.0, 528814.0, Decimal('1.19')),
 ('India', datetime.date(2022, 10, 9), 44612013.0, 528799.0, Decimal('1.19')),
 ('India', datetime.date(2022, 10, 8), 44609257.0, 528778.0, Decimal('1.19')),
 ('India', datetime.date(2022, 10, 7), 44606460.0, 528754.0, Decimal('1.19')),
 ('India', datetime.date(2022, 10, 6), 44604463.0, 528745.0, Decimal('1.19')),
 ('India', datetime.date(2022, 10, 5), 44601934.0, 528733.0, Decimal('1.19')),
 ('India', datetime.date(2022, 10, 4), 44599466.0, 528716.0, Decimal('1.19')),
 ('India', datetime.date(2022, 10, 3), 44597498.0, 528701.0, Decimal('1.19')),
 ('India', datetime.date(2022, 10, 2), 44594487.0, 528673.0, Decimal('1.19')),
 ('India', datetime.date(2022, 10, 1), 44591112.0, 528655.0, Decimal('1.19')),
 ('India', datetime.date(2022, 9, 30), 44587307.0, 528629.0, Decimal('1.19')),
 ('India', datetime.date(2022, 9, 29), 44583360.0, 528611.0, Decimal('1.19')),
 ('India', datetime.date(2022, 9, 28), 44579088.0, 528584.0, Decimal('1.19')),
 ('India', datetime.date(2022, 9, 27), 44575473.0, 528562.0, Decimal('1.19')),
 ('India', datetime.date(2022, 9, 26), 44572243.0, 528530.0, Decimal('1.19')),
 ('India', datetime.date(2022, 9, 25), 44568114.0, 528510.0, Decimal('1.19')),
 ('India', datetime.date(2022, 9, 24), 44563337.0, 528487.0, Decimal('1.19')),
 ('India', datetime.date(2022, 9, 23), 44558425.0, 528449.0, Decimal('1.19')),
 ('India', datetime.date(2022, 9, 22), 44553042.0, 528429.0, Decimal('1.19')),
 ('India', datetime.date(2022, 9, 21), 44547599.0, 528403.0, Decimal('1.19')),
 ('India', datetime.date(2022, 9, 20), 44543089.0, 528370.0, Decimal('1.19')),
 ('India', datetime.date(2022, 9, 19), 44539046.0, 528355.0, Decimal('1.19')),
 ('India', datetime.date(2022, 9, 18), 44534188.0, 528337.0, Decimal('1.19')),
 ('India', datetime.date(2022, 9, 17), 44528524.0, 528302.0, Decimal('1.19')),
 ('India', datetime.date(2022, 9, 16), 44522777.0, 528273.0, Decimal('1.19')),
 ('India', datetime.date(2022, 9, 15), 44516479.0, 528250.0, Decimal('1.19')),
 ('India', datetime.date(2022, 9, 14), 44510057.0, 528216.0, Decimal('1.19')),
 ('India', datetime.date(2022, 9, 13), 44504949.0, 528185.0, Decimal('1.19')),
 ('India', datetime.date(2022, 9, 12), 44500580.0, 528165.0, Decimal('1.19')),
 ('India', datetime.date(2022, 9, 11), 44495359.0, 528150.0, Decimal('1.19')),
 ('India', datetime.date(2022, 9, 10), 44490283.0, 528139.0, Decimal('1.19')),
 ('India', datetime.date(2022, 9, 9), 44484729.0, 528121.0, Decimal('1.19')),
 ('India', datetime.date(2022, 9, 8), 44478636.0, 528090.0, Decimal('1.19')),
 ('India', datetime.date(2022, 9, 7), 44472241.0, 528057.0, Decimal('1.19')),
 ('India', datetime.date(2022, 9, 6), 44466862.0, 528030.0, Decimal('1.19')),
 ('India', datetime.date(2022, 9, 5), 44462445.0, 528007.0, Decimal('1.19')),
 ('India', datetime.date(2022, 9, 4), 44456535.0, 527991.0, Decimal('1.19')),
 ('India', datetime.date(2022, 9, 3), 44449718.0, 527957.0, Decimal('1.19')),
 ('India', datetime.date(2022, 9, 2), 44442507.0, 527932.0, Decimal('1.19')),
 ('India', datetime.date(2022, 9, 1), 44436339.0, 527911.0, Decimal('1.19')),
 ('India', datetime.date(2022, 8, 31), 44428393.0, 527874.0, Decimal('1.19')),
 ('India', datetime.date(2022, 8, 30), 44421162.0, 527829.0, Decimal('1.19')),
 ('India', datetime.date(2022, 8, 29), 44415723.0, 527799.0, Decimal('1.19')),
 ('India', datetime.date(2022, 8, 28), 44408132.0, 527754.0, Decimal('1.19')),
 ('India', datetime.date(2022, 8, 27), 44398696.0, 527597.0, Decimal('1.19')),
 ('India', datetime.date(2022, 8, 26), 44389176.0, 527556.0, Decimal('1.19')),
 ('India', datetime.date(2022, 8, 25), 44378920.0, 527488.0, Decimal('1.19')),
 ('India', datetime.date(2022, 8, 24), 44368195.0, 527452.0, Decimal('1.19')),
 ('India', datetime.date(2022, 8, 23), 44357546.0, 527416.0, Decimal('1.19')),
 ('India', datetime.date(2022, 8, 22), 44348960.0, 527368.0, Decimal('1.19')),
 ('India', datetime.date(2022, 8, 21), 44339429.0, 527332.0, Decimal('1.19')),
 ('India', datetime.date(2022, 8, 20), 44327890.0, 527289.0, Decimal('1.19')),
 ('India', datetime.date(2022, 8, 19), 44314618.0, 527253.0, Decimal('1.19')),
 ('India', datetime.date(2022, 8, 18), 44298864.0, 527206.0, Decimal('1.19')),
 ('India', datetime.date(2022, 8, 17), 44286256.0, 527134.0, Decimal('1.19')),
 ('India', datetime.date(2022, 8, 16), 44277194.0, 527098.0, Decimal('1.19')),
 ('India', datetime.date(2022, 8, 15), 44268381.0, 527069.0, Decimal('1.19')),
 ('India', datetime.date(2022, 8, 14), 44253464.0, 527037.0, Decimal('1.19')),
 ('India', datetime.date(2022, 8, 13), 44239372.0, 526996.0, Decimal('1.19')),
 ('India', datetime.date(2022, 8, 12), 44223557.0, 526928.0, Decimal('1.19')),
 ('India', datetime.date(2022, 8, 11), 44206996.0, 526879.0, Decimal('1.19')),
 ('India', datetime.date(2022, 8, 10), 44190697.0, 526826.0, Decimal('1.19')),
 ('India', datetime.date(2022, 8, 9), 44174650.0, 526772.0, Decimal('1.19')),
 ('India', datetime.date(2022, 8, 8), 44161899.0, 526730.0, Decimal('1.19')),
 ('India', datetime.date(2022, 8, 7), 44145732.0, 526689.0, Decimal('1.19')),
 ('India', datetime.date(2022, 8, 6), 44126994.0, 526649.0, Decimal('1.19')),
 ('India', datetime.date(2022, 8, 5), 44107588.0, 526600.0, Decimal('1.19')),
 ('India', datetime.date(2022, 8, 4), 44087037.0, 526530.0, Decimal('1.19')),
 ('India', datetime.date(2022, 8, 3), 44067144.0, 526477.0, Decimal('1.19')),
 ('India', datetime.date(2023, 1, 8), 44679924.0, 530720.0, Decimal('1.19')),
 ('India', datetime.date(2023, 1, 6), 44679547.0, 530714.0, Decimal('1.19')),
 ('India', datetime.date(2022, 2, 19), 42802505.0, 511230.0, Decimal('1.19')),
 ('India', datetime.date(2022, 2, 18), 42780235.0, 510905.0, Decimal('1.19')),
 ('India', datetime.date(2022, 2, 17), 42754315.0, 510413.0, Decimal('1.19')),
 ('India', datetime.date(2022, 2, 16), 42723558.0, 509872.0, Decimal('1.19')),
 ('India', datetime.date(2022, 2, 15), 42692943.0, 509358.0, Decimal('1.19')),
 ('India', datetime.date(2022, 2, 14), 42665534.0, 509011.0, Decimal('1.19')),
 ('India', datetime.date(2022, 2, 13), 42631421.0, 508665.0, Decimal('1.19')),
 ('India', datetime.date(2022, 2, 12), 42586544.0, 507981.0, Decimal('1.19')),
 ('India', datetime.date(2022, 2, 11), 42536137.0, 507177.0, Decimal('1.19')),
 ('India', datetime.date(2022, 2, 10), 42478060.0, 506520.0, Decimal('1.19')),
 ('India', datetime.date(2022, 2, 9), 42410976.0, 505279.0, Decimal('1.19')),
 ('India', datetime.date(2022, 2, 8), 42339611.0, 504062.0, Decimal('1.19')),
 ('India', datetime.date(2022, 2, 7), 42272014.0, 502874.0, Decimal('1.19')),
 ('India', datetime.date(2022, 2, 6), 42188138.0, 501979.0, Decimal('1.19')),
 ('India', datetime.date(2022, 2, 5), 42080664.0, 501114.0, Decimal('1.19')),
 ('India', datetime.date(2022, 2, 4), 41952712.0, 500055.0, Decimal('1.19')),
 ('India', datetime.date(2022, 2, 3), 41803318.0, 498983.0, Decimal('1.19')),
 ('India', datetime.date(2023, 1, 5), 44679319.0, 530710.0, Decimal('1.19')),
 ('India', datetime.date(2023, 1, 4), 44679131.0, 530707.0, Decimal('1.19')),
 ('India', datetime.date(2021, 4, 19), 15061919.0, 178769.0, Decimal('1.19')),
 ('India', datetime.date(2023, 3, 5), 44687820.0, 530775.0, Decimal('1.19')),
 ('India', datetime.date(2023, 3, 6), 44688101.0, 530775.0, Decimal('1.19')),
 ('India', datetime.date(2023, 3, 7), 44688367.0, 530775.0, Decimal('1.19')),
 ('India', datetime.date(2023, 1, 3), 44678956.0, 530707.0, Decimal('1.19')),
 ('India', datetime.date(2023, 1, 2), 44678822.0, 530707.0, Decimal('1.19')),
 ('India', datetime.date(2023, 1, 1), 44678649.0, 530705.0, Decimal('1.19')),
 ('India', datetime.date(2022, 12, 31), 44678384.0, 530702.0, Decimal('1.19')),
 ('India', datetime.date(2022, 12, 30), 44678158.0, 530699.0, Decimal('1.19')),
 ('India', datetime.date(2022, 12, 29), 44677915.0, 530698.0, Decimal('1.19')),
 ('India', datetime.date(2021, 6, 3), 28441986.0, 337989.0, Decimal('1.19')),
 ('India', datetime.date(2022, 12, 28), 44677647.0, 530696.0, Decimal('1.19')),
 ('India', datetime.date(2022, 12, 27), 44677459.0, 530696.0, Decimal('1.19')),
 ('India', datetime.date(2022, 12, 26), 44677302.0, 530695.0, Decimal('1.19')),
 ('India', datetime.date(2022, 12, 25), 44677106.0, 530693.0, Decimal('1.19')),
 ('India', datetime.date(2022, 12, 24), 44676879.0, 530691.0, Decimal('1.19')),
 ('India', datetime.date(2022, 12, 23), 44676678.0, 530690.0, Decimal('1.19')),
 ('India', datetime.date(2022, 12, 22), 44676515.0, 530681.0, Decimal('1.19')),
 ('India', datetime.date(2022, 12, 21), 44676330.0, 530680.0, Decimal('1.19')),
 ('India', datetime.date(2022, 12, 20), 44676199.0, 530677.0, Decimal('1.19')),
 ('India', datetime.date(2022, 12, 19), 44676087.0, 530674.0, Decimal('1.19')),
 ('India', datetime.date(2022, 12, 18), 44675952.0, 530672.0, Decimal('1.19')),
 ('India', datetime.date(2022, 12, 17), 44675776.0, 530667.0, Decimal('1.19')),
 ('India', datetime.date(2022, 12, 16), 44675609.0, 530663.0, Decimal('1.19')),
 ('India', datetime.date(2022, 12, 15), 44675447.0, 530663.0, Decimal('1.19')),
 ('India', datetime.date(2022, 12, 14), 44675247.0, 530658.0, Decimal('1.19')),
 ('India', datetime.date(2022, 12, 13), 44675095.0, 530658.0, Decimal('1.19')),
 ('India', datetime.date(2022, 12, 12), 44674981.0, 530658.0, Decimal('1.19')),
 ('India', datetime.date(2022, 12, 11), 44674822.0, 530658.0, Decimal('1.19')),
 ('India', datetime.date(2022, 12, 10), 44674649.0, 530654.0, Decimal('1.19')),
 ('India', datetime.date(2022, 12, 9), 44674439.0, 530653.0, Decimal('1.19')),
 ('India', datetime.date(2022, 12, 8), 44674190.0, 530647.0, Decimal('1.19')),
 ('India', datetime.date(2022, 12, 7), 44673949.0, 530638.0, Decimal('1.19')),
 ('India', datetime.date(2022, 12, 6), 44673783.0, 530633.0, Decimal('1.19')),
 ('India', datetime.date(2022, 12, 5), 44673618.0, 530630.0, Decimal('1.19')),
 ('India', datetime.date(2021, 6, 4), 28574350.0, 340702.0, Decimal('1.19')),
 ('India', datetime.date(2023, 3, 4), 44687496.0, 530775.0, Decimal('1.19')),
 ('India', datetime.date(2023, 3, 3), 44687162.0, 530772.0, Decimal('1.19')),
 ('India', datetime.date(2023, 3, 2), 44686879.0, 530772.0, Decimal('1.19')),
 ('India', datetime.date(2023, 3, 1), 44686611.0, 530772.0, Decimal('1.19')),
 ('India', datetime.date(2023, 2, 28), 44686371.0, 530771.0, Decimal('1.19')),
 ('India', datetime.date(2023, 2, 27), 44686202.0, 530770.0, Decimal('1.19')),
 ('India', datetime.date(2023, 2, 26), 44686017.0, 530769.0, Decimal('1.19')),
 ('India', datetime.date(2023, 2, 25), 44685799.0, 530764.0, Decimal('1.19')),
 ('India', datetime.date(2023, 2, 24), 44685619.0, 530764.0, Decimal('1.19')),
 ('India', datetime.date(2023, 2, 23), 44685450.0, 530763.0, Decimal('1.19')),
 ('India', datetime.date(2023, 2, 22), 44685257.0, 530762.0, Decimal('1.19')),
 ('India', datetime.date(2023, 2, 21), 44685132.0, 530761.0, Decimal('1.19')),
 ('India', datetime.date(2023, 2, 20), 44685037.0, 530761.0, Decimal('1.19')),
 ('India', datetime.date(2023, 2, 19), 44684917.0, 530760.0, Decimal('1.19')),
 ('India', datetime.date(2023, 2, 18), 44684775.0, 530757.0, Decimal('1.19')),
 ('India', datetime.date(2023, 2, 17), 44684658.0, 530757.0, Decimal('1.19')),
 ('India', datetime.date(2023, 2, 16), 44684502.0, 530757.0, Decimal('1.19')),
 ('India', datetime.date(2023, 2, 15), 44684376.0, 530756.0, Decimal('1.19')),
 ('India', datetime.date(2023, 2, 14), 44684274.0, 530753.0, Decimal('1.19')),
 ('India', datetime.date(2023, 2, 13), 44684197.0, 530750.0, Decimal('1.19')),
 ('India', datetime.date(2023, 2, 12), 44684118.0, 530750.0, Decimal('1.19')),
 ('India', datetime.date(2023, 2, 11), 44683994.0, 530750.0, Decimal('1.19')),
 ('India', datetime.date(2023, 2, 10), 44683862.0, 530750.0, Decimal('1.19')),
 ('India', datetime.date(2023, 2, 9), 44683748.0, 530748.0, Decimal('1.19')),
 ('India', datetime.date(2023, 2, 8), 44683639.0, 530746.0, Decimal('1.19')),
 ('India', datetime.date(2023, 2, 7), 44683543.0, 530745.0, Decimal('1.19')),
 ('India', datetime.date(2023, 2, 6), 44683454.0, 530745.0, Decimal('1.19')),
 ('India', datetime.date(2023, 2, 5), 44683363.0, 530745.0, Decimal('1.19')),

####  Ques 3: Analysisng Total Percentage population infected on daily basis.

In [26]:
%sql select location, date, population, total_cases, ROUND(CAST((total_cases/population)*100 as numeric), 2)  as percent_population_infected from covid_deaths where location='India' order by population

 * postgresql://postgres:***@localhost/Covidanalysis
1166 rows affected.

[('India', datetime.date(2020, 1, 20), 1417173120, None, None),
 ('India', datetime.date(2020, 1, 3), 1417173120, None, None),
 ('India', datetime.date(2020, 1, 4), 1417173120, None, None),
 ('India', datetime.date(2020, 1, 5), 1417173120, None, None),
 ('India', datetime.date(2020, 1, 6), 1417173120, None, None),
 ('India', datetime.date(2020, 1, 7), 1417173120, None, None),
 ('India', datetime.date(2020, 1, 8), 1417173120, None, None),
 ('India', datetime.date(2020, 1, 9), 1417173120, None, None),
 ('India', datetime.date(2020, 1, 10), 1417173120, None, None),
 ('India', datetime.date(2020, 1, 11), 1417173120, None, None),
 ('India', datetime.date(2020, 1, 12), 1417173120, None, None),
 ('India', datetime.date(2020, 1, 13), 1417173120, None, None),
 ('India', datetime.date(2020, 1, 14), 1417173120, None, None),
 ('India', datetime.date(2020, 1, 15), 1417173120, None, None),
 ('India', datetime.date(2020, 1, 16), 1417173120, None, None),
 ('India', datetime.date(2020, 1, 17), 1417173120, None, None),
 ('India', datetime.date(2020, 1, 18), 1417173120, None, None),
 ('India', datetime.date(2020, 1, 19), 1417173120, None, None),
 ('India', datetime.date(2020, 1, 21), 1417173120, None, None),
 ('India', datetime.date(2020, 1, 22), 1417173120, None, None),
 ('India', datetime.date(2020, 1, 23), 1417173120, None, None),
 ('India', datetime.date(2020, 1, 24), 1417173120, None, None),
 ('India', datetime.date(2020, 1, 25), 1417173120, None, None),
 ('India', datetime.date(2020, 1, 26), 1417173120, None, None),
 ('India', datetime.date(2020, 1, 27), 1417173120, None, None),
 ('India', datetime.date(2020, 1, 28), 1417173120, None, None),
 ('India', datetime.date(2020, 1, 29), 1417173120, None, None),
 ('India', datetime.date(2020, 1, 30), 1417173120, 1.0, Decimal('0.00')),
 ('India', datetime.date(2020, 1, 31), 1417173120, 5.0, Decimal('0.00')),
 ('India', datetime.date(2020, 2, 1), 1417173120, 5.0, Decimal('0.00')),
 ('India', datetime.date(2020, 2, 2), 1417173120, 2.0, Decimal('0.00')),
 ('India', datetime.date(2020, 2, 3), 1417173120, 3.0, Decimal('0.00')),
 ('India', datetime.date(2020, 2, 4), 1417173120, 7.0, Decimal('0.00')),
 ('India', datetime.date(2020, 2, 5), 1417173120, 7.0, Decimal('0.00')),
 ('India', datetime.date(2020, 2, 6), 1417173120, 7.0, Decimal('0.00')),
 ('India', datetime.date(2020, 2, 7), 1417173120, 7.0, Decimal('0.00')),
 ('India', datetime.date(2020, 2, 8), 1417173120, 7.0, Decimal('0.00')),
 ('India', datetime.date(2020, 2, 9), 1417173120, 7.0, Decimal('0.00')),
 ('India', datetime.date(2020, 2, 10), 1417173120, 7.0, Decimal('0.00')),
 ('India', datetime.date(2020, 2, 11), 1417173120, 7.0, Decimal('0.00')),
 ('India', datetime.date(2020, 2, 12), 1417173120, 7.0, Decimal('0.00')),
 ('India', datetime.date(2020, 2, 13), 1417173120, 7.0, Decimal('0.00')),
 ('India', datetime.date(2020, 2, 14), 1417173120, 7.0, Decimal('0.00')),
 ('India', datetime.date(2020, 2, 15), 1417173120, 7.0, Decimal('0.00')),
 ('India', datetime.date(2020, 2, 16), 1417173120, 7.0, Decimal('0.00')),
 ('India', datetime.date(2020, 2, 17), 1417173120, 7.0, Decimal('0.00')),
 ('India', datetime.date(2020, 2, 18), 1417173120, 7.0, Decimal('0.00')),
 ('India', datetime.date(2020, 2, 19), 1417173120, 7.0, Decimal('0.00')),
 ('India', datetime.date(2020, 2, 20), 1417173120, 7.0, Decimal('0.00')),
 ('India', datetime.date(2020, 2, 21), 1417173120, 7.0, Decimal('0.00')),
 ('India', datetime.date(2020, 2, 22), 1417173120, 7.0, Decimal('0.00')),
 ('India', datetime.date(2020, 2, 23), 1417173120, 7.0, Decimal('0.00')),
 ('India', datetime.date(2020, 2, 24), 1417173120, 7.0, Decimal('0.00')),
 ('India', datetime.date(2020, 2, 25), 1417173120, 7.0, Decimal('0.00')),
 ('India', datetime.date(2020, 2, 26), 1417173120, 7.0, Decimal('0.00')),
 ('India', datetime.date(2020, 2, 27), 1417173120, 7.0, Decimal('0.00')),
 ('India', datetime.date(2020, 2, 28), 1417173120, 7.0, Decimal('0.00')),
 ('India', datetime.date(2020, 2, 29), 1417173120, 7.0, Decimal('0.00')),
 ('India', datetime.date(2020, 3, 1), 1417173120, 7.0, Decimal('0.00')),
 ('India', datetime.date(2020, 3, 2), 1417173120, 5.0, Decimal('0.00')),
 ('India', datetime.date(2020, 3, 3), 1417173120, 9.0, Decimal('0.00')),
 ('India', datetime.date(2020, 3, 4), 1417173120, 28.0, Decimal('0.00')),
 ('India', datetime.date(2020, 3, 5), 1417173120, 29.0, Decimal('0.00')),
 ('India', datetime.date(2020, 3, 6), 1417173120, 31.0, Decimal('0.00')),
 ('India', datetime.date(2020, 3, 7), 1417173120, 34.0, Decimal('0.00')),
 ('India', datetime.date(2020, 3, 8), 1417173120, 39.0, Decimal('0.00')),
 ('India', datetime.date(2020, 3, 9), 1417173120, 44.0, Decimal('0.00')),
 ('India', datetime.date(2020, 3, 10), 1417173120, 50.0, Decimal('0.00')),
 ('India', datetime.date(2020, 3, 11), 1417173120, 60.0, Decimal('0.00')),
 ('India', datetime.date(2020, 3, 12), 1417173120, 73.0, Decimal('0.00')),
 ('India', datetime.date(2020, 3, 13), 1417173120, 81.0, Decimal('0.00')),
 ('India', datetime.date(2020, 3, 14), 1417173120, 84.0, Decimal('0.00')),
 ('India', datetime.date(2020, 3, 15), 1417173120, 107.0, Decimal('0.00')),
 ('India', datetime.date(2020, 3, 16), 1417173120, 114.0, Decimal('0.00')),
 ('India', datetime.date(2020, 3, 17), 1417173120, 137.0, Decimal('0.00')),
 ('India', datetime.date(2020, 3, 18), 1417173120, 151.0, Decimal('0.00')),
 ('India', datetime.date(2020, 3, 19), 1417173120, 173.0, Decimal('0.00')),
 ('India', datetime.date(2020, 3, 20), 1417173120, 223.0, Decimal('0.00')),
 ('India', datetime.date(2020, 3, 21), 1417173120, 283.0, Decimal('0.00')),
 ('India', datetime.date(2020, 3, 22), 1417173120, 360.0, Decimal('0.00')),
 ('India', datetime.date(2020, 3, 23), 1417173120, 434.0, Decimal('0.00')),
 ('India', datetime.date(2020, 3, 24), 1417173120, 519.0, Decimal('0.00')),
 ('India', datetime.date(2020, 3, 25), 1417173120, 606.0, Decimal('0.00')),
 ('India', datetime.date(2020, 3, 26), 1417173120, 649.0, Decimal('0.00')),
 ('India', datetime.date(2020, 3, 27), 1417173120, 724.0, Decimal('0.00')),
 ('India', datetime.date(2020, 3, 28), 1417173120, 909.0, Decimal('0.00')),
 ('India', datetime.date(2020, 3, 29), 1417173120, 979.0, Decimal('0.00')),
 ('India', datetime.date(2020, 3, 30), 1417173120, 1071.0, Decimal('0.00')),
 ('India', datetime.date(2020, 3, 31), 1417173120, 1251.0, Decimal('0.00')),
 ('India', datetime.date(2020, 4, 1), 1417173120, 1637.0, Decimal('0.00')),
 ('India', datetime.date(2020, 4, 2), 1417173120, 1965.0, Decimal('0.00')),
 ('India', datetime.date(2020, 4, 3), 1417173120, 2301.0, Decimal('0.00')),
 ('India', datetime.date(2020, 4, 4), 1417173120, 2902.0, Decimal('0.00')),
 ('India', datetime.date(2020, 4, 5), 1417173120, 3374.0, Decimal('0.00')),
 ('India', datetime.date(2020, 4, 6), 1417173120, 4067.0, Decimal('0.00')),
 ('India', datetime.date(2020, 4, 7), 1417173120, 4421.0, Decimal('0.00')),
 ('India', datetime.date(2020, 4, 8), 1417173120, 5274.0, Decimal('0.00')),
 ('India', datetime.date(2020, 4, 9), 1417173120, 5865.0, Decimal('0.00')),
 ('India', datetime.date(2020, 4, 10), 1417173120, 6412.0, Decimal('0.00')),
 ('India', datetime.date(2020, 4, 11), 1417173120, 7447.0, Decimal('0.00')),
 ('India', datetime.date(2020, 4, 12), 1417173120, 8356.0, Decimal('0.00')),
 ('India', datetime.date(2020, 4, 13), 1417173120, 9152.0, Decimal('0.00')),
 ('India', datetime.date(2020, 4, 14), 1417173120, 10363.0, Decimal('0.00')),
 ('India', datetime.date(2020, 4, 15), 1417173120, 11439.0, Decimal('0.00')),
 ('India', datetime.date(2020, 4, 16), 1417173120, 12380.0, Decimal('0.00')),
 ('India', datetime.date(2020, 4, 17), 1417173120, 13387.0, Decimal('0.00')),
 ('India', datetime.date(2020, 4, 18), 1417173120, 14378.0, Decimal('0.00')),
 ('India', datetime.date(2020, 4, 19), 1417173120, 15712.0, Decimal('0.00')),
 ('India', datetime.date(2020, 4, 20), 1417173120, 17265.0, Decimal('0.00')),
 ('India', datetime.date(2020, 4, 21), 1417173120, 18601.0, Decimal('0.00')),
 ('India', datetime.date(2020, 4, 22), 1417173120, 19984.0, Decimal('0.00')),
 ('India', datetime.date(2020, 4, 23), 1417173120, 21393.0, Decimal('0.00')),
 ('India', datetime.date(2020, 4, 24), 1417173120, 23077.0, Decimal('0.00')),
 ('India', datetime.date(2020, 4, 25), 1417173120, 24506.0, Decimal('0.00')),
 ('India', datetime.date(2020, 4, 26), 1417173120, 26496.0, Decimal('0.00')),
 ('India', datetime.date(2020, 4, 27), 1417173120, 27892.0, Decimal('0.00')),
 ('India', datetime.date(2020, 4, 28), 1417173120, 29435.0, Decimal('0.00')),
 ('India', datetime.date(2020, 4, 29), 1417173120, 31332.0, Decimal('0.00')),
 ('India', datetime.date(2020, 4, 30), 1417173120, 33050.0, Decimal('0.00')),
 ('India', datetime.date(2020, 5, 1), 1417173120, 35043.0, Decimal('0.00')),
 ('India', datetime.date(2020, 5, 2), 1417173120, 37336.0, Decimal('0.00')),
 ('India', datetime.date(2020, 5, 3), 1417173120, 39980.0, Decimal('0.00')),
 ('India', datetime.date(2020, 5, 4), 1417173120, 42533.0, Decimal('0.00')),
 ('India', datetime.date(2020, 5, 5), 1417173120, 46433.0, Decimal('0.00')),
 ('India', datetime.date(2020, 5, 6), 1417173120, 49391.0, Decimal('0.00')),
 ('India', datetime.date(2020, 5, 7), 1417173120, 52952.0, Decimal('0.00')),
 ('India', datetime.date(2020, 5, 8), 1417173120, 56342.0, Decimal('0.00')),
 ('India', datetime.date(2020, 5, 9), 1417173120, 59662.0, Decimal('0.00')),
 ('India', datetime.date(2020, 5, 10), 1417173120, 62939.0, Decimal('0.00')),
 ('India', datetime.date(2020, 5, 11), 1417173120, 67152.0, Decimal('0.00')),
 ('India', datetime.date(2020, 5, 12), 1417173120, 70756.0, Decimal('0.00')),
 ('India', datetime.date(2020, 5, 13), 1417173120, 74281.0, Decimal('0.01')),
 ('India', datetime.date(2020, 5, 14), 1417173120, 78003.0, Decimal('0.01')),
 ('India', datetime.date(2020, 5, 15), 1417173120, 81970.0, Decimal('0.01')),
 ('India', datetime.date(2020, 5, 16), 1417173120, 85940.0, Decimal('0.01')),
 ('India', datetime.date(2020, 5, 17), 1417173120, 90927.0, Decimal('0.01')),
 ('India', datetime.date(2020, 5, 18), 1417173120, 96169.0, Decimal('0.01')),
 ('India', datetime.date(2020, 5, 19), 1417173120, 101139.0, Decimal('0.01')),
 ('India', datetime.date(2020, 5, 20), 1417173120, 106750.0, Decimal('0.01')),
 ('India', datetime.date(2020, 5, 21), 1417173120, 112359.0, Decimal('0.01')),
 ('India', datetime.date(2020, 5, 22), 1417173120, 118447.0, Decimal('0.01')),
 ('India', datetime.date(2020, 5, 23), 1417173120, 125101.0, Decimal('0.01')),
 ('India', datetime.date(2020, 5, 24), 1417173120, 131868.0, Decimal('0.01')),
 ('India', datetime.date(2020, 5, 25), 1417173120, 138845.0, Decimal('0.01')),
 ('India', datetime.date(2020, 5, 26), 1417173120, 145380.0, Decimal('0.01')),
 ('India', datetime.date(2020, 5, 27), 1417173120, 151767.0, Decimal('0.01')),
 ('India', datetime.date(2020, 5, 28), 1417173120, 158333.0, Decimal('0.01')),
 ('India', datetime.date(2020, 5, 29), 1417173120, 165799.0, Decimal('0.01')),
 ('India', datetime.date(2020, 5, 30), 1417173120, 173763.0, Decimal('0.01')),
 ('India', datetime.date(2020, 5, 31), 1417173120, 182143.0, Decimal('0.01')),
 ('India', datetime.date(2020, 6, 1), 1417173120, 190535.0, Decimal('0.01')),
 ('India', datetime.date(2020, 6, 2), 1417173120, 198706.0, Decimal('0.01')),
 ('India', datetime.date(2020, 6, 3), 1417173120, 207615.0, Decimal('0.01')),
 ('India', datetime.date(2020, 6, 4), 1417173120, 216919.0, Decimal('0.02')),
 ('India', datetime.date(2020, 6, 5), 1417173120, 226770.0, Decimal('0.02')),
 ('India', datetime.date(2020, 6, 6), 1417173120, 236657.0, Decimal('0.02')),
 ('India', datetime.date(2020, 6, 7), 1417173120, 246628.0, Decimal('0.02')),
 ('India', datetime.date(2020, 6, 8), 1417173120, 256611.0, Decimal('0.02')),
 ('India', datetime.date(2020, 6, 9), 1417173120, 266598.0, Decimal('0.02')),
 ('India', datetime.date(2020, 6, 10), 1417173120, 276583.0, Decimal('0.02')),
 ('India', datetime.date(2020, 6, 11), 1417173120, 286579.0, Decimal('0.02')),
 ('India', datetime.date(2020, 6, 12), 1417173120, 297535.0, Decimal('0.02')),
 ('India', datetime.date(2020, 6, 13), 1417173120, 308993.0, Decimal('0.02')),
 ('India', datetime.date(2020, 6, 14), 1417173120, 320922.0, Decimal('0.02')),
 ('India', datetime.date(2020, 6, 15), 1417173120, 332424.0, Decimal('0.02')),
 ('India', datetime.date(2020, 6, 16), 1417173120, 343091.0, Decimal('0.02')),
 ('India', datetime.date(2020, 6, 17), 1417173120, 354065.0, Decimal('0.02')),
 ('India', datetime.date(2020, 6, 18), 1417173120, 366946.0, Decimal('0.03')),
 ('India', datetime.date(2020, 6, 19), 1417173120, 380532.0, Decimal('0.03')),
 ('India', datetime.date(2020, 6, 20), 1417173120, 395048.0, Decimal('0.03')),
 ('India', datetime.date(2020, 6, 21), 1417173120, 410461.0, Decimal('0.03')),
 ('India', datetime.date(2020, 6, 22), 1417173120, 425282.0, Decimal('0.03')),
 ('India', datetime.date(2020, 6, 23), 1417173120, 440215.0, Decimal('0.03')),
 ('India', datetime.date(2020, 6, 24), 1417173120, 456183.0, Decimal('0.03')),
 ('India', datetime.date(2020, 6, 25), 1417173120, 473105.0, Decimal('0.03')),
 ('India', datetime.date(2020, 6, 26), 1417173120, 490401.0, Decimal('0.03')),
 ('India', datetime.date(2020, 6, 27), 1417173120, 508953.0, Decimal('0.04')),
 ('India', datetime.date(2020, 6, 28), 1417173120, 528859.0, Decimal('0.04')),
 ('India', datetime.date(2020, 6, 29), 1417173120, 548318.0, Decimal('0.04')),
 ('India', datetime.date(2020, 6, 30), 1417173120, 566840.0, Decimal('0.04')),
 ('India', datetime.date(2020, 7, 1), 1417173120, 585493.0, Decimal('0.04')),
 ('India', datetime.date(2020, 7, 2), 1417173120, 604641.0, Decimal('0.04')),
 ('India', datetime.date(2020, 7, 3), 1417173120, 625544.0, Decimal('0.04')),
 ('India', datetime.date(2020, 7, 4), 1417173120, 648315.0, Decimal('0.05')),
 ('India', datetime.date(2020, 7, 5), 1417173120, 673165.0, Decimal('0.05')),
 ('India', datetime.date(2020, 7, 6), 1417173120, 697413.0, Decimal('0.05')),
 ('India', datetime.date(2020, 7, 7), 1417173120, 719665.0, Decimal('0.05')),
 ('India', datetime.date(2020, 7, 8), 1417173120, 742417.0, Decimal('0.05')),
 ('India', datetime.date(2020, 7, 9), 1417173120, 767296.0, Decimal('0.05')),
 ('India', datetime.date(2020, 7, 10), 1417173120, 793802.0, Decimal('0.06')),
 ('India', datetime.date(2020, 7, 11), 1417173120, 820916.0, Decimal('0.06')),
 ('India', datetime.date(2020, 7, 12), 1417173120, 849553.0, Decimal('0.06')),
 ('India', datetime.date(2020, 7, 13), 1417173120, 878254.0, Decimal('0.06')),
 ('India', datetime.date(2020, 7, 14), 1417173120, 906752.0, Decimal('0.06')),
 ('India', datetime.date(2020, 7, 15), 1417173120, 936181.0, Decimal('0.07')),
 ('India', datetime.date(2020, 7, 16), 1417173120, 968876.0, Decimal('0.07')),
 ('India', datetime.date(2020, 7, 17), 1417173120, 1003832.0, Decimal('0.07')),
 ('India', datetime.date(2020, 7, 18), 1417173120, 1038716.0, Decimal('0.07')),
 ('India', datetime.date(2020, 7, 19), 1417173120, 1077618.0, Decimal('0.08')),
 ('India', datetime.date(2020, 7, 20), 1417173120, 1118043.0, Decimal('0.08')),
 ('India', datetime.date(2020, 7, 21), 1417173120, 1155191.0, Decimal('0.08')),
 ('India', datetime.date(2020, 7, 22), 1417173120, 1192915.0, Decimal('0.08')),
 ('India', datetime.date(2020, 7, 23), 1417173120, 1238635.0, Decimal('0.09')),
 ('India', datetime.date(2020, 7, 24), 1417173120, 1287945.0, Decimal('0.09')),
 ('India', datetime.date(2020, 7, 25), 1417173120, 1336861.0, Decimal('0.09')),
 ('India', datetime.date(2020, 7, 26), 1417173120, 1385522.0, Decimal('0.10')),
 ('India', datetime.date(2020, 7, 27), 1417173120, 1435453.0, Decimal('0.10')),
 ('India', datetime.date(2020, 7, 28), 1417173120, 1483156.0, Decimal('0.10')),
 ('India', datetime.date(2020, 7, 29), 1417173120, 1531669.0, Decimal('0.11')),
 ('India', datetime.date(2020, 7, 30), 1417173120, 1583792.0, Decimal('0.11')),
 ('India', datetime.date(2020, 7, 31), 1417173120, 1638870.0, Decimal('0.12')),
 ('India', datetime.date(2020, 8, 1), 1417173120, 1695988.0, Decimal('0.12')),
 ('India', datetime.date(2020, 8, 2), 1417173120, 1750723.0, Decimal('0.12')),
 ('India', datetime.date(2020, 8, 3), 1417173120, 1803695.0, Decimal('0.13')),
 ('India', datetime.date(2020, 8, 4), 1417173120, 1855745.0, Decimal('0.13')),
 ('India', datetime.date(2020, 8, 5), 1417173120, 1908254.0, Decimal('0.13')),
 ('India', datetime.date(2020, 8, 6), 1417173120, 1964536.0, Decimal('0.14')),
 ('India', datetime.date(2020, 8, 7), 1417173120, 2027074.0, Decimal('0.14')),
 ('India', datetime.date(2020, 8, 8), 1417173120, 2088611.0, Decimal('0.15')),
 ('India', datetime.date(2020, 8, 9), 1417173120, 2153010.0, Decimal('0.15')),
 ('India', datetime.date(2020, 8, 10), 1417173120, 2215074.0, Decimal('0.16')),
 ('India', datetime.date(2020, 8, 11), 1417173120, 2268675.0, Decimal('0.16')),
 ('India', datetime.date(2020, 8, 12), 1417173120, 2329638.0, Decimal('0.16')),
 ('India', datetime.date(2020, 8, 13), 1417173120, 2396637.0, Decimal('0.17')),
 ('India', datetime.date(2020, 8, 14), 1417173120, 2461190.0, Decimal('0.17')),
 ('India', datetime.date(2020, 8, 15), 1417173120, 2526192.0, Decimal('0.18')),
 ('India', datetime.date(2020, 8, 16), 1417173120, 2589682.0, Decimal('0.18')),
 ('India', datetime.date(2020, 8, 17), 1417173120, 2647663.0, Decimal('0.19')),
 ('India', datetime.date(2020, 8, 18), 1417173120, 2702742.0, Decimal('0.19')),
 ('India', datetime.date(2020, 8, 19), 1417173120, 2767273.0, Decimal('0.20')),
 ('India', datetime.date(2020, 8, 20), 1417173120, 2836925.0, Decimal('0.20')),
 ('India', datetime.date(2020, 8, 21), 1417173120, 2905823.0, Decimal('0.21')),
 ('India', datetime.date(2020, 8, 22), 1417173120, 2975701.0, Decimal('0.21')),
 ('India', datetime.date(2020, 8, 23), 1417173120, 3044940.0, Decimal('0.21')),
 ('India', datetime.date(2020, 8, 24), 1417173120, 3106348.0, Decimal('0.22')),
 ('India', datetime.date(2020, 8, 25), 1417173120, 3167323.0, Decimal('0.22')),
 ('India', datetime.date(2020, 8, 26), 1417173120, 3234474.0, Decimal('0.23')),
 ('India', datetime.date(2020, 8, 27), 1417173120, 3310234.0, Decimal('0.23')),
 ('India', datetime.date(2020, 8, 28), 1417173120, 3387500.0, Decimal('0.24')),
 ('India', datetime.date(2020, 8, 29), 1417173120, 3463972.0, Decimal('0.24')),
 ('India', datetime.date(2020, 8, 30), 1417173120, 3542733.0, Decimal('0.25')),
 ('India', datetime.date(2020, 8, 31), 1417173120, 3621245.0, Decimal('0.26')),
 ('India', datetime.date(2020, 9, 1), 1417173120, 3691166.0, Decimal('0.26')),
 ('India', datetime.date(2020, 9, 2), 1417173120, 3769523.0, Decimal('0.27')),
 ('India', datetime.date(2020, 9, 3), 1417173120, 3853406.0, Decimal('0.27')),
 ('India', datetime.date(2020, 9, 4), 1417173120, 3936747.0, Decimal('0.28')),
 ('India', datetime.date(2020, 9, 5), 1417173120, 4023179.0, Decimal('0.28')),
 ('India', datetime.date(2020, 9, 6), 1417173120, 4113811.0, Decimal('0.29')),
 ('India', datetime.date(2020, 9, 7), 1417173120, 4204613.0, Decimal('0.30')),
 ('India', datetime.date(2020, 9, 8), 1417173120, 4280422.0, Decimal('0.30')),
 ('India', datetime.date(2020, 9, 9), 1417173120, 4370128.0, Decimal('0.31')),
 ('India', datetime.date(2020, 9, 10), 1417173120, 4465863.0, Decimal('0.32')),
 ('India', datetime.date(2020, 9, 11), 1417173120, 4562414.0, Decimal('0.32')),
 ('India', datetime.date(2020, 9, 12), 1417173120, 4659984.0, Decimal('0.33')),
 ('India', datetime.date(2020, 9, 13), 1417173120, 4754356.0, Decimal('0.34')),
 ('India', datetime.date(2020, 9, 14), 1417173120, 4846427.0, Decimal('0.34')),
 ('India', datetime.date(2020, 9, 15), 1417173120, 4930236.0, Decimal('0.35')),
 ('India', datetime.date(2020, 9, 16), 1417173120, 5020359.0, Decimal('0.35')),
 ('India', datetime.date(2020, 9, 17), 1417173120, 5118253.0, Decimal('0.36')),
 ('India', datetime.date(2020, 9, 18), 1417173120, 5214677.0, Decimal('0.37')),
 ('India', datetime.date(2020, 9, 19), 1417173120, 5308014.0, Decimal('0.37')),
 ('India', datetime.date(2020, 9, 20), 1417173120, 5400619.0, Decimal('0.38')),

#### Ques4: which country has the highest infection rate as compared to population

#### Step 1: Find out the population corresponding to country

In [41]:
%sql select location, max(population) as population from covid_deaths group by location;

 * postgresql://postgres:***@localhost/Covidanalysis
255 rows affected.

[('Afghanistan', 41128772),
 ('Africa', 1426736614),
 ('Albania', 2842318),
 ('Algeria', 44903228),
 ('American Samoa', 44295),
 ('Andorra', 79843),
 ('Angola', 35588996),
 ('Anguilla', 15877),
 ('Antigua and Barbuda', 93772),
 ('Argentina', 45510324),
 ('Armenia', 2780472),
 ('Aruba', 106459),
 ('Asia', 4721383370),
 ('Australia', 26177410),
 ('Austria', 8939617),
 ('Azerbaijan', 10358078),
 ('Bahamas', 409989),
 ('Bahrain', 1472237),
 ('Bangladesh', 171186368),
 ('Barbados', 281646),
 ('Belarus', 9534956),
 ('Belgium', 11655923),
 ('Belize', 405285),
 ('Benin', 13352864),
 ('Bermuda', 64207),
 ('Bhutan', 782457),
 ('Bolivia', 12224114),
 ('Bonaire Sint Eustatius and Saba', 27052),
 ('Bosnia and Herzegovina', 3233530),
 ('Botswana', 2630300),
 ('Brazil', 215313504),
 ('British Virgin Islands', 31332),
 ('Brunei', 449002),
 ('Bulgaria', 6781955),
 ('Burkina Faso', 22673764),
 ('Burundi', 12889583),
 ('Cambodia', 16767851),
 ('Cameroon', 27914542),
 ('Canada', 38454328),
 ('Cape Verde', 593162),
 ('Cayman Islands', 68722),
 ('Central African Republic', 5579148),
 ('Chad', 17723312),
 ('Chile', 19603736),
 ('China', 1425887360),
 ('Colombia', 51874028),
 ('Comoros', 836783),
 ('Congo', 5970430),
 ('Cook Islands', 17032),
 ('Costa Rica', 5180836),
 ("Cote d'Ivoire", 28160548),
 ('Croatia', 4030361),
 ('Cuba', 11212198),
 ('Curacao', 191173),
 ('Cyprus', 896007),
 ('Czechia', 10493990),
 ('Democratic Republic of Congo', 99010216),
 ('Denmark', 5882259),
 ('Djibouti', 1120851),
 ('Dominica', 72758),
 ('Dominican Republic', 11228821),
 ('Ecuador', 18001002),
 ('Egypt', 110990096),
 ('El Salvador', 6336393),
 ('England', 56550000),
 ('Equatorial Guinea', 1674916),
 ('Eritrea', 3684041),
 ('Estonia', 1326064),
 ('Eswatini', 1201680),
 ('Ethiopia', 123379928),
 ('Europe', 744807803),
 ('European Union', 450146793),
 ('Faeroe Islands', 53117),
 ('Falkland Islands', 3801),
 ('Fiji', 929769),
 ('Finland', 5540745),
 ('France', 67813000),
 ('French Guiana', 304568),
 ('French Polynesia', 306292),
 ('Gabon', 2388997),
 ('Gambia', 2705995),
 ('Georgia', 3744385),
 ('Germany', 83369840),
 ('Ghana', 33475870),
 ('Gibraltar', 32677),
 ('Greece', 10384972),
 ('Greenland', 56494),
 ('Grenada', 125459),
 ('Guadeloupe', 395762),
 ('Guam', 171783),
 ('Guatemala', 17843914),
 ('Guernsey', 63329),
 ('Guinea', 13859349),
 ('Guinea-Bissau', 2105580),
 ('Guyana', 808727),
 ('Haiti', 11585003),
 ('High income', 1250514600),
 ('Honduras', 10432858),
 ('Hong Kong', 7488863),
 ('Hungary', 9967304),
 ('Iceland', 372903),
 ('India', 1417173120),
 ('Indonesia', 275501344),
 ('Iran', 88550568),
 ('Iraq', 44496124),
 ('Ireland', 5023108),
 ('Isle of Man', 84534),
 ('Israel', 9449000),
 ('Italy', 59037472),
 ('Jamaica', 2827382),
 ('Japan', 123951696),
 ('Jersey', 110796),
 ('Jordan', 11285875),
 ('Kazakhstan', 19397998),
 ('Kenya', 54027484),
 ('Kiribati', 131237),
 ('Kosovo', 1782115),
 ('Kuwait', 4268886),
 ('Kyrgyzstan', 6630621),
 ('Laos', 7529477),
 ('Latvia', 1850654),
 ('Lebanon', 5489744),
 ('Lesotho', 2305826),
 ('Liberia', 5302690),
 ('Libya', 6812344),
 ('Liechtenstein', 39355),
 ('Lithuania', 2750058),
 ('Low income', 737604900),
 ('Lower middle income', 3432097300),
 ('Luxembourg', 647601),
 ('Macao', 695180),
 ('Madagascar', 29611718),
 ('Malawi', 20405318),
 ('Malaysia', 33938216),
 ('Maldives', 523798),
 ('Mali', 22593598),
 ('Malta', 533293),
 ('Marshall Islands', 41593),
 ('Martinique', 367512),
 ('Mauritania', 4736146),
 ('Mauritius', 1299478),
 ('Mayotte', 326113),
 ('Mexico', 127504120),
 ('Micronesia (country)', 114178),
 ('Moldova', 3272993),
 ('Monaco', 36491),
 ('Mongolia', 3398373),
 ('Montenegro', 627082),
 ('Montserrat', 4413),
 ('Morocco', 37457976),
 ('Mozambique', 32969520),
 ('Myanmar', 54179312),
 ('Namibia', 2567024),
 ('Nauru', 12691),
 ('Nepal', 30547586),
 ('Netherlands', 17564020),
 ('New Caledonia', 289959),
 ('New Zealand', 5185289),
 ('Nicaragua', 6948395),
 ('Niger', 26207982),
 ('Nigeria', 218541216),
 ('Niue', 1952),
 ('North America', 600323657),
 ('North Korea', 26069416),
 ('North Macedonia', 2093606),
 ('Northern Cyprus', 382836),
 ('Northern Ireland', 1896000),
 ('Northern Mariana Islands', 49574),
 ('Norway', 5434324),
 ('Oceania', 45038860),
 ('Oman', 4576300),
 ('Pakistan', 235824864),
 ('Palau', 18084),
 ('Palestine', 5250076),
 ('Panama', 4408582),
 ('Papua New Guinea', 10142625),
 ('Paraguay', 6780745),
 ('Peru', 34049588),
 ('Philippines', 115559008),
 ('Pitcairn', 47),
 ('Poland', 39857144),
 ('Portugal', 10270857),
 ('Puerto Rico', 3252412),
 ('Qatar', 2695131),
 ('Reunion', 974062),
 ('Romania', 19659270),
 ('Russia', 144713312),
 ('Rwanda', 13776702),
 ('Saint Barthelemy', 10994),
 ('Saint Helena', 5401),
 ('Saint Kitts and Nevis', 47681),
 ('Saint Lucia', 179872),
 ('Saint Martin (French part)', 31816),
 ('Saint Pierre and Miquelon', 5885),
 ('Saint Vincent and the Grenadines', 103959),
 ('Samoa', 222390),
 ('San Marino', 33690),
 ('Sao Tome and Principe', 227393),
 ('Saudi Arabia', 36408824),
 ('Scotland', 5466000),
 ('Senegal', 17316452),
 ('Serbia', 6871547),
 ('Seychelles', 107135),
 ('Sierra Leone', 8605723),
 ('Singapore', 5637022),
 ('Sint Maarten (Dutch part)', 44192),
 ('Slovakia', 5643455),
 ('Slovenia', 2119843),
 ('Solomon Islands', 724272),
 ('Somalia', 17597508),
 ('South Africa', 59893884),
 ('South America', 436816679),
 ('South Korea', 51815808),
 ('South Sudan', 10913172),
 ('Spain', 47558632),
 ('Sri Lanka', 21832150),
 ('Sudan', 46874200),
 ('Suriname', 618046),
 ('Sweden', 10549349),
 ('Switzerland', 8740471),
 ('Syria', 22125242),
 ('Taiwan', 23893396),
 ('Tajikistan', 9952789),
 ('Tanzania', 65497752),
 ('Thailand', 71697024),
 ('Timor', 1341298),
 ('Togo', 8848700),
 ('Tokelau', 1893),
 ('Tonga', 106867),
 ('Trinidad and Tobago', 1531043),
 ('Tunisia', 12356116),
 ('Turkey', 85341248),
 ('Turkmenistan', 6430777),
 ('Turks and Caicos Islands', 45726),
 ('Tuvalu', 11335),
 ('Uganda', 47249588),
 ('Ukraine', 39701744),
 ('United Arab Emirates', 9441138),
 ('United Kingdom', 67508936),
 ('United States', 338289856),
 ('United States Virgin Islands', 99479),
 ('Upper middle income', 2525921300),
 ('Uruguay', 3422796),
 ('Uzbekistan', 34627648),
 ('Vanuatu', 326744),
 ('Vatican', 808),
 ('Venezuela', 28301700),
 ('Vietnam', 98186856),
 ('Wales', 3170000),
 ('Wallis and Futuna', 11596),
 ('Western Sahara', 576005),
 ('World', 7975105024),
 ('Yemen', 33696612),
 ('Zambia', 20017670),
 ('Zimbabwe', 16320539)]

#### Step 2: Now find out total cases correspond to country

In [42]:
%sql select location, max(population) as population, max(total_cases) as total_cases,  from covid_deaths group by location;

 * postgresql://postgres:***@localhost/Covidanalysis
255 rows affected.

[('Afghanistan', 41128772, 209414.0),
 ('Africa', 1426736614, 13053883.0),
 ('Albania', 2842318, 333532.0),
 ('Algeria', 44903228, 271463.0),
 ('American Samoa', 44295, 8320.0),
 ('Andorra', 79843, 47890.0),
 ('Angola', 35588996, 105277.0),
 ('Anguilla', 15877, 3904.0),
 ('Antigua and Barbuda', 93772, 9106.0),
 ('Argentina', 45510324, 10044957.0),
 ('Armenia', 2780472, 447308.0),
 ('Aruba', 106459, 44044.0),
 ('Asia', 4721383370, 294846415.0),
 ('Australia', 26177410, 11380700.0),
 ('Austria', 8939617, 5943417.0),
 ('Azerbaijan', 10358078, 828730.0),
 ('Bahamas', 409989, 37491.0),
 ('Bahrain', 1472237, 696614.0),
 ('Bangladesh', 171186368, 2037871.0),
 ('Barbados', 281646, 106645.0),
 ('Belarus', 9534956, 994037.0),
 ('Belgium', 11655923, 4727795.0),
 ('Belize', 405285, 70757.0),
 ('Benin', 13352864, 27999.0),
 ('Bermuda', 64207, 18814.0),
 ('Bhutan', 782457, 62627.0),
 ('Bolivia', 12224114, 1193970.0),
 ('Bonaire Sint Eustatius and Saba', 27052, 11804.0),
 ('Bosnia and Herzegovina', 3233530, 401729.0),
 ('Botswana', 2630300, 329758.0),
 ('Brazil', 215313504, 37076053.0),
 ('British Virgin Islands', 31332, 7305.0),
 ('Brunei', 449002, 279661.0),
 ('Bulgaria', 6781955, 1297243.0),
 ('Burkina Faso', 22673764, 22056.0),
 ('Burundi', 12889583, 53631.0),
 ('Cambodia', 16767851, 138719.0),
 ('Cameroon', 27914542, 124392.0),
 ('Canada', 38454328, 4600615.0),
 ('Cape Verde', 593162, 63244.0),
 ('Cayman Islands', 68722, 31472.0),
 ('Central African Republic', 5579148, 15367.0),
 ('Chad', 17723312, 7678.0),
 ('Chile', 19603736, 5182360.0),
 ('China', 1425887360, 99109603.0),
 ('Colombia', 51874028, 6360089.0),
 ('Comoros', 836783, 9001.0),
 ('Congo', 5970430, 25087.0),
 ('Cook Islands', 17032, 7031.0),
 ('Costa Rica', 5180836, 1209725.0),
 ("Cote d'Ivoire", 28160548, 88208.0),
 ('Croatia', 4030361, 1269326.0),
 ('Cuba', 11212198, 1112631.0),
 ('Curacao', 191173, 45786.0),
 ('Cyprus', 896007, 650685.0),
 ('Czechia', 10493990, 4615945.0),
 ('Democratic Republic of Congo', 99010216, 95748.0),
 ('Denmark', 5882259, 3403958.0),
 ('Djibouti', 1120851, 15690.0),
 ('Dominica', 72758, 15760.0),
 ('Dominican Republic', 11228821, 660790.0),
 ('Ecuador', 18001002, 1057121.0),
 ('Egypt', 110990096, 515759.0),
 ('El Salvador', 6336393, 201785.0),
 ('England', 56550000, None),
 ('Equatorial Guinea', 1674916, 17130.0),
 ('Eritrea', 3684041, 10189.0),
 ('Estonia', 1326064, 615433.0),
 ('Eswatini', 1201680, 74199.0),
 ('Ethiopia', 123379928, 500014.0),
 ('Europe', 744807803, 246769927.0),
 ('European Union', 450146793, 182481130.0),
 ('Faeroe Islands', 53117, 34658.0),
 ('Falkland Islands', 3801, 1923.0),
 ('Fiji', 929769, 68897.0),
 ('Finland', 5540745, 1462976.0),
 ('France', 67813000, 38538948.0),
 ('French Guiana', 304568, 98041.0),
 ('French Polynesia', 306292, 78055.0),
 ('Gabon', 2388997, 48981.0),
 ('Gambia', 2705995, 12598.0),
 ('Georgia', 3744385, 1827537.0),
 ('Germany', 83369840, 38221663.0),
 ('Ghana', 33475870, 171172.0),
 ('Gibraltar', 32677, 20433.0),
 ('Greece', 10384972, 5896788.0),
 ('Greenland', 56494, 11971.0),
 ('Grenada', 125459, 19680.0),
 ('Guadeloupe', 395762, 201886.0),
 ('Guam', 171783, 50869.0),
 ('Guatemala', 17843914, 1237564.0),
 ('Guernsey', 63329, 34991.0),
 ('Guinea', 13859349, 38267.0),
 ('Guinea-Bissau', 2105580, 8960.0),
 ('Guyana', 808727, 73075.0),
 ('Haiti', 11585003, 34202.0),
 ('High income', 1250514600, 416752372.0),
 ('Honduras', 10432858, 472219.0),
 ('Hong Kong', 7488863, None),
 ('Hungary', 9967304, 2195926.0),
 ('Iceland', 372903, 209137.0),
 ('India', 1417173120, 44688367.0),
 ('Indonesia', 275501344, 6737606.0),
 ('Iran', 88550568, 7570743.0),
 ('Iraq', 44496124, 2465545.0),
 ('Ireland', 5023108, 1703850.0),
 ('Isle of Man', 84534, 38008.0),
 ('Israel', 9449000, 4801511.0),
 ('Italy', 59037472, 25603510.0),
 ('Jamaica', 2827382, 154287.0),
 ('Japan', 123951696, 33264491.0),
 ('Jersey', 110796, 66391.0),
 ('Jordan', 11285875, 1746997.0),
 ('Kazakhstan', 19397998, 1499224.0),
 ('Kenya', 54027484, 342932.0),
 ('Kiribati', 131237, 5014.0),
 ('Kosovo', 1782115, 273181.0),
 ('Kuwait', 4268886, 663860.0),
 ('Kyrgyzstan', 6630621, 206708.0),
 ('Laos', 7529477, 218020.0),
 ('Latvia', 1850654, 976162.0),
 ('Lebanon', 5489744, 1232517.0),
 ('Lesotho', 2305826, 34490.0),
 ('Liberia', 5302690, 8090.0),
 ('Libya', 6812344, 507187.0),
 ('Liechtenstein', 39355, 21432.0),
 ('Lithuania', 2750058, 1307021.0),
 ('Low income', 737604900, 2286826.0),
 ('Lower middle income', 3432097300, 96855618.0),
 ('Luxembourg', 647601, 317367.0),
 ('Macao', 695180, None),
 ('Madagascar', 29611718, 67865.0),
 ('Malawi', 20405318, 88605.0),
 ('Malaysia', 33938216, 5043978.0),
 ('Maldives', 523798, 185738.0),
 ('Mali', 22593598, 33051.0),
 ('Malta', 533293, 117610.0),
 ('Marshall Islands', 41593, 15649.0),
 ('Martinique', 367512, 229020.0),
 ('Mauritania', 4736146, 63439.0),
 ('Mauritius', 1299478, 296042.0),
 ('Mayotte', 326113, 42004.0),
 ('Mexico', 127504120, 7470653.0),
 ('Micronesia (country)', 114178, 23948.0),
 ('Moldova', 3272993, 611050.0),
 ('Monaco', 36491, 16119.0),
 ('Mongolia', 3398373, 1007900.0),
 ('Montenegro', 627082, 288622.0),
 ('Montserrat', 4413, 1403.0),
 ('Morocco', 37457976, 1272490.0),
 ('Mozambique', 32969520, 233214.0),
 ('Myanmar', 54179312, 633947.0),
 ('Namibia', 2567024, 171156.0),
 ('Nauru', 12691, 5247.0),
 ('Nepal', 30547586, 1001149.0),
 ('Netherlands', 17564020, 8598182.0),
 ('New Caledonia', 289959, 80017.0),
 ('New Zealand', 5185289, 2176499.0),
 ('Nicaragua', 6948395, 15655.0),
 ('Niger', 26207982, 9513.0),
 ('Nigeria', 218541216, 266598.0),
 ('Niue', 1952, 747.0),
 ('North America', 600323657, 122709749.0),
 ('North Korea', 26069416, None),
 ('North Macedonia', 2093606, 346852.0),
 ('Northern Cyprus', 382836, None),
 ('Northern Ireland', 1896000, None),
 ('Northern Mariana Islands', 49574, 13649.0),
 ('Norway', 5434324, 1479333.0),
 ('Oceania', 45038860, 14043499.0),
 ('Oman', 4576300, 399449.0),
 ('Pakistan', 235824864, 1577213.0),
 ('Palau', 18084, 5991.0),
 ('Palestine', 5250076, 703228.0),
 ('Panama', 4408582, 1031731.0),
 ('Papua New Guinea', 10142625, 46825.0),
 ('Paraguay', 6780745, 735709.0),
 ('Peru', 34049588, 4486832.0),
 ('Philippines', 115559008, 4077109.0),
 ('Pitcairn', 47, 4.0),
 ('Poland', 39857144, 6437598.0),
 ('Portugal', 10270857, 5570473.0),
 ('Puerto Rico', 3252412, 1100123.0),
 ('Qatar', 2695131, 494737.0),
 ('Reunion', 974062, 494595.0),
 ('Romania', 19659270, 3346046.0),
 ('Russia', 144713312, 22363740.0),
 ('Rwanda', 13776702, 133172.0),
 ('Saint Barthelemy', 10994, 5441.0),
 ('Saint Helena', 5401, 2166.0),
 ('Saint Kitts and Nevis', 47681, 6597.0),
 ('Saint Lucia', 179872, 30004.0),
 ('Saint Martin (French part)', 31816, 12271.0),
 ('Saint Pierre and Miquelon', 5885, 3415.0),
 ('Saint Vincent and the Grenadines', 103959, 9589.0),
 ('Samoa', 222390, 16427.0),
 ('San Marino', 33690, 23616.0),
 ('Sao Tome and Principe', 227393, 6281.0),
 ('Saudi Arabia', 36408824, 829882.0),
 ('Scotland', 5466000, None),
 ('Senegal', 17316452, 88921.0),
 ('Serbia', 6871547, 2497248.0),
 ('Seychelles', 107135, 50665.0),
 ('Sierra Leone', 8605723, 7760.0),
 ('Singapore', 5637022, 2230570.0),
 ('Sint Maarten (Dutch part)', 44192, 11020.0),
 ('Slovakia', 5643455, 1863590.0),
 ('Slovenia', 2119843, 1330654.0),
 ('Solomon Islands', 724272, 24575.0),
 ('Somalia', 17597508, 27324.0),
 ('South Africa', 59893884, 4061578.0),
 ('South America', 436816679, 67979025.0),
 ('South Korea', 51815808, 30581499.0),
 ('South Sudan', 10913172, 18368.0),
 ('Spain', 47558632, 13770429.0),
 ('Sri Lanka', 21832150, 672034.0),
 ('Sudan', 46874200, 63829.0),
 ('Suriname', 618046, 82467.0),
 ('Sweden', 10549349, 2698535.0),
 ('Switzerland', 8740471, 4391007.0),
 ('Syria', 22125242, 57423.0),
 ('Taiwan', 23893396, None),
 ('Tajikistan', 9952789, 17786.0),
 ('Tanzania', 65497752, 42846.0),
 ('Thailand', 71697024, 4728182.0),
 ('Timor', 1341298, 23419.0),
 ('Togo', 8848700, 39382.0),
 ('Tokelau', 1893, 5.0),
 ('Tonga', 106867, 16810.0),
 ('Trinidad and Tobago', 1531043, 189296.0),
 ('Tunisia', 12356116, 1150962.0),
 ('Turkey', 85341248, 17004677.0),
 ('Turkmenistan', 6430777, None),
 ('Turks and Caicos Islands', 45726, 6557.0),
 ('Tuvalu', 11335, 2779.0),
 ('Uganda', 47249588, 170409.0),
 ('Ukraine', 39701744, 5399231.0),
 ('United Arab Emirates', 9441138, 1052664.0),
 ('United Kingdom', 67508936, 24396534.0),
 ('United States', 338289856, 102247392.0),
 ('United States Virgin Islands', 99479, 24780.0),
 ('Upper middle income', 2525921300, 242304899.0),
 ('Uruguay', 3422796, 1034303.0),
 ('Uzbekistan', 34627648, 251247.0),
 ('Vanuatu', 326744, 12014.0),
 ('Vatican', 808, 26.0),
 ('Venezuela', 28301700, 552125.0),
 ('Vietnam', 98186856, 11526966.0),
 ('Wales', 3170000, None),
 ('Wallis and Futuna', 11596, 3427.0),
 ('Western Sahara', 576005, None),
 ('World', 7975105024, 759407939.0),
 ('Yemen', 33696612, 11945.0),
 ('Zambia', 20017670, 342954.0),
 ('Zimbabwe', 16320539, 264127.0)]

#### Step3

In [43]:
%sql select location, max(population) as population, max(total_cases) as total_cases, max((total_cases/population)*100) as percentPopulationInfected from covid_deaths group by location;

 * postgresql://postgres:***@localhost/Covidanalysis
255 rows affected.

[('Afghanistan', 41128772, 209414.0, 0.5091666729072291),
 ('Africa', 1426736614, 13053883.0, 0.9149469405850686),
 ('Albania', 2842318, 333532.0, 11.734506835617971),
 ('Algeria', 44903228, 271463.0, 0.6045511917316946),
 ('American Samoa', 44295, 8320.0, 18.78315837001919),
 ('Andorra', 79843, 47890.0, 59.98021116441016),
 ('Angola', 35588996, 105277.0, 0.2958133463500909),
 ('Anguilla', 15877, 3904.0, 24.589028153933363),
 ('Antigua and Barbuda', 93772, 9106.0, 9.710787868446872),
 ('Argentina', 45510324, 10044957.0, 22.071820451113467),
 ('Armenia', 2780472, 447308.0, 16.087484427104464),
 ('Aruba', 106459, 44044.0, 41.371795714782216),
 ('Asia', 4721383370, 294846415.0, 6.244915777724697),
 ('Australia', 26177410, 11380700.0, 43.47527123577161),
 ('Austria', 8939617, 5943417.0, 66.48402274952048),
 ('Azerbaijan', 10358078, 828730.0, 8.00080864422917),
 ('Bahamas', 409989, 37491.0, 9.144391678801139),
 ('Bahrain', 1472237, 696614.0, 47.31670240593056),
 ('Bangladesh', 171186368, 2037871.0, 1.190440000456111),
 ('Barbados', 281646, 106645.0, 37.864908431151164),
 ('Belarus', 9534956, 994037.0, 10.425187069557532),
 ('Belgium', 11655923, 4727795.0, 40.56130947330383),
 ('Belize', 405285, 70757.0, 17.458578531157087),
 ('Benin', 13352864, 27999.0, 0.2096853528950793),
 ('Bermuda', 64207, 18814.0, 29.302101017023062),
 ('Bhutan', 782457, 62627.0, 8.00389030962724),
 ('Bolivia', 12224114, 1193970.0, 9.767333648884492),
 ('Bonaire Sint Eustatius and Saba', 27052, 11804.0, 43.63448173887328),
 ('Bosnia and Herzegovina', 3233530, 401729.0, 12.423852569792148),
 ('Botswana', 2630300, 329758.0, 12.536896931908908),
 ('Brazil', 215313504, 37076053.0, 17.21956696222825),
 ('British Virgin Islands', 31332, 7305.0, 23.314821907315206),
 ('Brunei', 449002, 279661.0, 62.28502322929519),
 ('Bulgaria', 6781955, 1297243.0, 19.12786209876061),
 ('Burkina Faso', 22673764, 22056.0, 0.09727542370115523),
 ('Burundi', 12889583, 53631.0, 0.41608017885450604),
 ('Cambodia', 16767851, 138719.0, 0.8272914638852648),
 ('Cameroon', 27914542, 124392.0, 0.4456171983763875),
 ('Canada', 38454328, 4600615.0, 11.963841885365934),
 ('Cape Verde', 593162, 63244.0, 10.662179977813818),
 ('Cayman Islands', 68722, 31472.0, 45.79610605046419),
 ('Central African Republic', 5579148, 15367.0, 0.27543632110135813),
 ('Chad', 17723312, 7678.0, 0.04332147399989347),
 ('Chile', 19603736, 5182360.0, 26.435573300925906),
 ('China', 1425887360, 99109603.0, 6.950731578124095),
 ('Colombia', 51874028, 6360089.0, 12.260642262058386),
 ('Comoros', 836783, 9001.0, 1.0756671681905583),
 ('Congo', 5970430, 25087.0, 0.4201874906832506),
 ('Cook Islands', 17032, 7031.0, 41.28111789572569),
 ('Costa Rica', 5180836, 1209725.0, 23.34999602380774),
 ("Cote d'Ivoire", 28160548, 88208.0, 0.3132325407872034),
 ('Croatia', 4030361, 1269326.0, 31.494101893105853),
 ('Cuba', 11212198, 1112631.0, 9.923397713811333),
 ('Curacao', 191173, 45786.0, 23.95003478524687),
 ('Cyprus', 896007, 650685.0, 72.62052640213749),
 ('Czechia', 10493990, 4615945.0, 43.986558020352604),
 ('Democratic Republic of Congo', 99010216, 95748.0, 0.09670517232282375),
 ('Denmark', 5882259, 3403958.0, 57.86821015531618),
 ('Djibouti', 1120851, 15690.0, 1.3998292368923255),
 ('Dominica', 72758, 15760.0, 21.6608482915968),
 ('Dominican Republic', 11228821, 660790.0, 5.88476742126355),
 ('Ecuador', 18001002, 1057121.0, 5.872567538184819),
 ('Egypt', 110990096, 515759.0, 0.46468920974714717),
 ('El Salvador', 6336393, 201785.0, 3.184540479102228),
 ('England', 56550000, None, None),
 ('Equatorial Guinea', 1674916, 17130.0, 1.0227378567044556),
 ('Eritrea', 3684041, 10189.0, 0.2765712976592823),
 ('Estonia', 1326064, 615433.0, 46.410505073661604),
 ('Eswatini', 1201680, 74199.0, 6.174605552226883),
 ('Ethiopia', 123379928, 500014.0, 0.4052636503402725),
 ('Europe', 744807803, 246769927.0, 33.13202761921118),
 ('European Union', 450146793, 182481130.0, 40.53813841121823),
 ('Faeroe Islands', 53117, 34658.0, 65.24841387879586),
 ('Falkland Islands', 3801, 1923.0, 50.59194948697711),
 ('Fiji', 929769, 68897.0, 7.410120148122814),
 ('Finland', 5540745, 1462976.0, 26.403958312465203),
 ('France', 67813000, 38538948.0, 56.83120935513839),
 ('French Guiana', 304568, 98041.0, 32.19018412965249),
 ('French Polynesia', 306292, 78055.0, 25.483852010499785),
 ('Gabon', 2388997, 48981.0, 2.0502746550121245),
 ('Gambia', 2705995, 12598.0, 0.4655588794509968),
 ('Georgia', 3744385, 1827537.0, 48.80740094835333),
 ('Germany', 83369840, 38221663.0, 45.84591142312376),
 ('Ghana', 33475870, 171172.0, 0.5113295039083375),
 ('Gibraltar', 32677, 20433.0, 62.53022003243872),
 ('Greece', 10384972, 5896788.0, 56.78193451075265),
 ('Greenland', 56494, 11971.0, 21.189860870180905),
 ('Grenada', 125459, 19680.0, 15.686399540885867),
 ('Guadeloupe', 395762, 201886.0, 51.011971841662415),
 ('Guam', 171783, 50869.0, 29.61235977948924),
 ('Guatemala', 17843914, 1237564.0, 6.935496326646722),
 ('Guernsey', 63329, 34991.0, 55.252727818219135),
 ('Guinea', 13859349, 38267.0, 0.27610964988326653),
 ('Guinea-Bissau', 2105580, 8960.0, 0.4255359568384958),
 ('Guyana', 808727, 73075.0, 9.03580565506036),
 ('Haiti', 11585003, 34202.0, 0.29522650965217706),
 ('High income', 1250514600, 416752372.0, 33.32646991886381),
 ('Honduras', 10432858, 472219.0, 4.526266915547015),
 ('Hong Kong', 7488863, None, None),
 ('Hungary', 9967304, 2195926.0, 22.031293517284112),
 ('Iceland', 372903, 209137.0, 56.08348551768154),
 ('India', 1417173120, 44688367.0, 3.1533456547637595),
 ('Indonesia', 275501344, 6737606.0, 2.445580083994073),
 ('Iran', 88550568, 7570743.0, 8.549626694658807),
 ('Iraq', 44496124, 2465545.0, 5.541033192014657),
 ('Ireland', 5023108, 1703850.0, 33.92023424541141),
 ('Isle of Man', 84534, 38008.0, 44.96179052215676),
 ('Israel', 9449000, 4801511.0, 50.815017462165315),
 ('Italy', 59037472, 25603510.0, 43.368235685972465),
 ('Jamaica', 2827382, 154287.0, 5.456885557027667),
 ('Japan', 123951696, 33264491.0, 26.83665659564674),
 ('Jersey', 110796, 66391.0, 59.92183833351385),
 ('Jordan', 11285875, 1746997.0, 15.479499817249437),
 ('Kazakhstan', 19397998, 1499224.0, 7.728756338669589),
 ('Kenya', 54027484, 342932.0, 0.6347362020411685),
 ('Kiribati', 131237, 5014.0, 3.820568894442878),
 ('Kosovo', 1782115, 273181.0, 15.329033199316541),
 ('Kuwait', 4268886, 663860.0, 15.551129732674987),
 ('Kyrgyzstan', 6630621, 206708.0, 3.1174757236162343),
 ('Laos', 7529477, 218020.0, 2.895553037747509),
 ('Latvia', 1850654, 976162.0, 52.74686678331012),
 ('Lebanon', 5489744, 1232517.0, 22.45126548706096),
 ('Lesotho', 2305826, 34490.0, 1.4957763508608195),
 ('Liberia', 5302690, 8090.0, 0.15256407596898933),
 ('Libya', 6812344, 507187.0, 7.445117275346049),
 ('Liechtenstein', 39355, 21432.0, 54.458137466649724),
 ('Lithuania', 2750058, 1307021.0, 47.52703397528343),
 ('Low income', 737604900, 2286826.0, 0.31003400329905617),
 ('Lower middle income', 3432097300, 96855618.0, 2.822053384092578),
 ('Luxembourg', 647601, 317367.0, 49.006564227047214),
 ('Macao', 695180, None, None),
 ('Madagascar', 29611718, 67865.0, 0.22918292008589303),
 ('Malawi', 20405318, 88605.0, 0.4342250387864575),
 ('Malaysia', 33938216, 5043978.0, 14.862236718630111),
 ('Maldives', 523798, 185738.0, 35.4598528440353),
 ('Mali', 22593598, 33051.0, 0.1462848015619292),
 ('Malta', 533293, 117610.0, 22.05354279917419),
 ('Marshall Islands', 41593, 15649.0, 37.62411944317554),
 ('Martinique', 367512, 229020.0, 62.31633252791745),
 ('Mauritania', 4736146, 63439.0, 1.3394646195450899),
 ('Mauritius', 1299478, 296042.0, 22.781609230783438),
 ('Mayotte', 326113, 42004.0, 12.880197968188941),
 ('Mexico', 127504120, 7470653.0, 5.859146355427574),
 ('Micronesia (country)', 114178, 23948.0, 20.974268247823574),
 ('Moldova', 3272993, 611050.0, 18.669456366084496),
 ('Monaco', 36491, 16119.0, 44.1725356937327),
 ('Mongolia', 3398373, 1007900.0, 29.658310020706967),
 ('Montenegro', 627082, 288622.0, 46.026197530785446),
 ('Montserrat', 4413, 1403.0, 31.792431452526625),
 ('Morocco', 37457976, 1272490.0, 3.397113608060404),
 ('Mozambique', 32969520, 233214.0, 0.7073624365777846),
 ('Myanmar', 54179312, 633947.0, 1.1700905319727943),
 ('Namibia', 2567024, 171156.0, 6.66748733163383),
 ('Nauru', 12691, 5247.0, 41.344259711606654),
 ('Nepal', 30547586, 1001149.0, 3.2773424387773225),
 ('Netherlands', 17564020, 8598182.0, 48.95338310933374),
 ('New Caledonia', 289959, 80017.0, 27.595970464789847),
 ('New Zealand', 5185289, 2176499.0, 41.97449746773999),
 ('Nicaragua', 6948395, 15655.0, 0.22530382915766878),
 ('Niger', 26207982, 9513.0, 0.03629810185309193),
 ('Nigeria', 218541216, 266598.0, 0.1219898035160562),
 ('Niue', 1952, 747.0, 38.26844262295082),
 ('North America', 600323657, 122709749.0, 20.440598595300735),
 ('North Korea', 26069416, None, None),
 ('North Macedonia', 2093606, 346852.0, 16.567205099717903),
 ('Northern Cyprus', 382836, None, None),
 ('Northern Ireland', 1896000, None, None),
 ('Northern Mariana Islands', 49574, 13649.0, 27.532577560818172),
 ('Norway', 5434324, 1479333.0, 27.22202430329881),
 ('Oceania', 45038860, 14043499.0, 31.180849160036466),
 ('Oman', 4576300, 399449.0, 8.72864541223259),
 ('Pakistan', 235824864, 1577213.0, 0.6688069159662486),
 ('Palau', 18084, 5991.0, 33.12873258128732),
 ('Palestine', 5250076, 703228.0, 13.394625144474098),
 ('Panama', 4408582, 1031731.0, 23.402785748342662),
 ('Papua New Guinea', 10142625, 46825.0, 0.4616654958652222),
 ('Paraguay', 6780745, 735709.0, 10.849972974945969),
 ('Peru', 34049588, 4486832.0, 13.17734593440602),
 ('Philippines', 115559008, 4077109.0, 3.52816199322168),
 ('Pitcairn', 47, 4.0, 8.51063829787234),
 ('Poland', 39857144, 6437598.0, 16.15167910676189),
 ('Portugal', 10270857, 5570473.0, 54.235717623174),
 ('Puerto Rico', 3252412, 1100123.0, 33.82483522997701),
 ('Qatar', 2695131, 494737.0, 18.35669583408005),
 ('Reunion', 974062, 494595.0, 50.7765419449686),
 ('Romania', 19659270, 3346046.0, 17.0201945443549),
 ('Russia', 144713312, 22363740.0, 15.453823626122245),
 ('Rwanda', 13776702, 133172.0, 0.9666464441199353),
 ('Saint Barthelemy', 10994, 5441.0, 49.490631253410946),
 ('Saint Helena', 5401, 2166.0, 40.10368450286984),
 ('Saint Kitts and Nevis', 47681, 6597.0, 13.83569975461924),
 ('Saint Lucia', 179872, 30004.0, 16.68075075609322),
 ('Saint Martin (French part)', 31816, 12271.0, 38.56864470706562),
 ('Saint Pierre and Miquelon', 5885, 3415.0, 58.028887000849615),
 ('Saint Vincent and the Grenadines', 103959, 9589.0, 9.223828624746295),
 ('Samoa', 222390, 16427.0, 7.386573137281352),
 ('San Marino', 33690, 23616.0, 70.0979519145147),
 ('Sao Tome and Principe', 227393, 6281.0, 2.7621782552673126),
 ('Saudi Arabia', 36408824, 829882.0, 2.279343051563544),
 ('Scotland', 5466000, None, None),
 ('Senegal', 17316452, 88921.0, 0.5135058844617824),
 ('Serbia', 6871547, 2497248.0, 36.34186013717144),
 ('Seychelles', 107135, 50665.0, 47.29080132543053),
 ('Sierra Leone', 8605723, 7760.0, 0.09017255145209763),
 ('Singapore', 5637022, 2230570.0, 39.570007000150085),
 ('Sint Maarten (Dutch part)', 44192, 11020.0, 24.936640115858076),
 ('Slovakia', 5643455, 1863590.0, 33.02214689405692),
 ('Slovenia', 2119843, 1330654.0, 62.77134674596184),
 ('Solomon Islands', 724272, 24575.0, 3.3930622749464288),
 ('Somalia', 17597508, 27324.0, 0.15527198510152687),
 ('South Africa', 59893884, 4061578.0, 6.781290056260168),
 ('South America', 436816679, 67979025.0, 15.562369357237845),
 ('South Korea', 51815808, 30581499.0, 59.01963161512409),
 ('South Sudan', 10913172, 18368.0, 0.16831036842450572),
 ('Spain', 47558632, 13770429.0, 28.95463645800409),
 ('Sri Lanka', 21832150, 672034.0, 3.07818515354649),
 ('Sudan', 46874200, 63829.0, 0.13617085731596484),
 ('Suriname', 618046, 82467.0, 13.343181575481436),
 ('Sweden', 10549349, 2698535.0, 25.58010925603087),
 ('Switzerland', 8740471, 4391007.0, 50.23764737621119),
 ('Syria', 22125242, 57423.0, 0.2595361442826253),
 ('Taiwan', 23893396, None, None),
 ('Tajikistan', 9952789, 17786.0, 0.1787036779338937),
 ('Tanzania', 65497752, 42846.0, 0.06541598557458889),
 ('Thailand', 71697024, 4728182.0, 6.594669815026075),
 ('Timor', 1341298, 23419.0, 1.745995297092816),
 ('Togo', 8848700, 39382.0, 0.4450597262874773),
 ('Tokelau', 1893, 5.0, 0.26413100898045433),
 ('Tonga', 106867, 16810.0, 15.729832408507772),
 ('Trinidad and Tobago', 1531043, 189296.0, 12.363859146999792),
 ('Tunisia', 12356116, 1150962.0, 9.314917406084566),
 ('Turkey', 85341248, 17004677.0, 19.925507768529467),
 ('Turkmenistan', 6430777, None, None),
 ('Turks and Caicos Islands', 45726, 6557.0, 14.339762935747716),
 ('Tuvalu', 11335, 2779.0, 24.51698279664755),
 ('Uganda', 47249588, 170409.0, 0.3606571130313348),
 ('Ukraine', 39701744, 5399231.0, 13.599480667650269),
 ('United Arab Emirates', 9441138, 1052664.0, 11.149757582189775),
 ('United Kingdom', 67508936, 24396534.0, 36.138229167172774),
 ('United States', 338289856, 102247392.0, 30.224788058675927),
 ('United States Virgin Islands', 99479, 24780.0, 24.909779953558036),
 ('Upper middle income', 2525921300, 242304899.0, 9.592733510739231),
 ('Uruguay', 3422796, 1034303.0, 30.218073177601003),
 ('Uzbekistan', 34627648, 251247.0, 0.7255676157964872),
 ('Vanuatu', 326744, 12014.0, 3.6768846558773842),
 ('Vatican', 808, 26.0, 3.217821782178218),
 ('Venezuela', 28301700, 552125.0, 1.950854542306646),
 ('Vietnam', 98186856, 11526966.0, 11.739825949819597),
 ('Wales', 3170000, None, None),
 ('Wallis and Futuna', 11596, 3427.0, 29.553294239392898),
 ('Western Sahara', 576005, None, None),
 ('World', 7975105024, 759407939.0, 9.522231202155513),
 ('Yemen', 33696612, 11945.0, 0.03544866765833907),
 ('Zambia', 20017670, 342954.0, 1.7132563380253547),
 ('Zimbabwe', 16320539, 264127.0, 1.6183717951962249)]

#### Thus, the above query showed us how much % of population got infected in respective countries

#### Ques5: Finding out number of death count per population

In [44]:
covid_deaths_df

,iso_code,continent,location,date,population,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,...,new_deaths_smoothed_per_million,reproduction_rate,icu_patients,icu_patients_per_million,hosp_patients,hosp_patients_per_million,weekly_icu_admissions,weekly_icu_admissions_per_million,weekly_hosp_admissions,weekly_hosp_admissions_per_million
0,AFG,Asia,Afghanistan,2020-01-03,41128772,NaN,0.0,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AFG,Asia,Afghanistan,2020-01-04,41128772,NaN,0.0,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AFG,Asia,Afghanistan,2020-01-05,41128772,NaN,0.0,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AFG,Asia,Afghanistan,2020-01-06,41128772,NaN,0.0,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AFG,Asia,Afghanistan,2020-01-07,41128772,NaN,0.0,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
293696,ZWE,Africa,Zimbabwe,2023-03-03,16320539,264127.0,0.0,11.571,5668.0,0.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
293697,ZWE,Africa,Zimbabwe,2023-03-04,16320539,264127.0,0.0,4.571,5668.0,0.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
293698,ZWE,Africa,Zimbabwe,2023-03-05,16320539,264127.0,0.0,2.714,5668.0,0.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
293699,ZWE,Africa,Zimbabwe,2023-03-06,16320539,264127.0,0.0,0.000,5668.0,0.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
293700,ZWE,Africa,Zimbabwe,2023-03-07,16320539,264127.0,0.0,0.000,5668.0,0.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
%sql select location, max(population) as population,  max(total_cases) as totalCases, max(total_deaths) as totalDeaths from covid_deaths group by location order by totalDeaths

 * postgresql://postgres:***@localhost/Covidanalysis
255 rows affected.

[('Nauru', 12691, 5247.0, 1.0),
 ('Cook Islands', 17032, 7031.0, 2.0),
 ('Saint Pierre and Miquelon', 5885, 3415.0, 2.0),
 ('Saint Barthelemy', 10994, 5441.0, 5.0),
 ('Wallis and Futuna', 11596, 3427.0, 7.0),
 ('Montserrat', 4413, 1403.0, 8.0),
 ('Palau', 18084, 5991.0, 9.0),
 ('Tonga', 106867, 16810.0, 12.0),
 ('Anguilla', 15877, 3904.0, 12.0),
 ('Vanuatu', 326744, 12014.0, 14.0),
 ('Burundi', 12889583, 53631.0, 15.0),
 ('Marshall Islands', 41593, 15649.0, 17.0),
 ('Kiribati', 131237, 5014.0, 18.0),
 ('Bhutan', 782457, 62627.0, 21.0),
 ('Greenland', 56494, 11971.0, 21.0),
 ('Faeroe Islands', 53117, 34658.0, 28.0),
 ('Samoa', 222390, 16427.0, 29.0),
 ('American Samoa', 44295, 8320.0, 34.0),
 ('Cayman Islands', 68722, 31472.0, 37.0),
 ('Turks and Caicos Islands', 45726, 6557.0, 38.0),
 ('Bonaire Sint Eustatius and Saba', 27052, 11804.0, 41.0),
 ('Northern Mariana Islands', 49574, 13649.0, 41.0),
 ('Saint Martin (French part)', 31816, 12271.0, 46.0),
 ('Saint Kitts and Nevis', 47681, 6597.0, 46.0),
 ('Micronesia (country)', 114178, 23948.0, 61.0),
 ('British Virgin Islands', 31332, 7305.0, 64.0),
 ('Guernsey', 63329, 34991.0, 66.0),
 ('Monaco', 36491, 16119.0, 67.0),
 ('Dominica', 72758, 15760.0, 74.0),
 ('Sao Tome and Principe', 227393, 6281.0, 77.0),
 ('Liechtenstein', 39355, 21432.0, 87.0),
 ('Sint Maarten (Dutch part)', 44192, 11020.0, 90.0),
 ('Eritrea', 3684041, 10189.0, 103.0),
 ('Gibraltar', 32677, 20433.0, 111.0),
 ('Central African Republic', 5579148, 15367.0, 113.0),
 ('Isle of Man', 84534, 38008.0, 116.0),
 ('San Marino', 33690, 23616.0, 122.0),
 ('Saint Vincent and the Grenadines', 103959, 9589.0, 123.0),
 ('Tajikistan', 9952789, 17786.0, 125.0),
 ('Sierra Leone', 8605723, 7760.0, 126.0),
 ('United States Virgin Islands', 99479, 24780.0, 130.0),
 ('Timor', 1341298, 23419.0, 138.0),
 ('South Sudan', 10913172, 18368.0, 138.0),
 ('Antigua and Barbuda', 93772, 9106.0, 146.0),
 ('Brunei', 449002, 279661.0, 150.0),
 ('Solomon Islands', 724272, 24575.0, 153.0),
 ('Andorra', 79843, 47890.0, 159.0),
 ('Bermuda', 64207, 18814.0, 160.0),
 ('Comoros', 836783, 9001.0, 161.0),
 ('Jersey', 110796, 66391.0, 161.0),
 ('Benin', 13352864, 27999.0, 163.0),
 ('Seychelles', 107135, 50665.0, 172.0),
 ('Guinea-Bissau', 2105580, 8960.0, 176.0),
 ('Equatorial Guinea', 1674916, 17130.0, 183.0),
 ('Mayotte', 326113, 42004.0, 187.0),
 ('Djibouti', 1120851, 15690.0, 189.0),
 ('Chad', 17723312, 7678.0, 194.0),
 ('Grenada', 125459, 19680.0, 238.0),
 ('Nicaragua', 6948395, 15655.0, 245.0),
 ('Iceland', 372903, 209137.0, 263.0),
 ('Aruba', 106459, 44044.0, 282.0),
 ('Togo', 8848700, 39382.0, 290.0),
 ('Liberia', 5302690, 8090.0, 294.0),
 ('Curacao', 191173, 45786.0, 301.0),
 ('Gabon', 2388997, 48981.0, 306.0),
 ('Maldives', 523798, 185738.0, 311.0),
 ('New Caledonia', 289959, 80017.0, 314.0),
 ('Niger', 26207982, 9513.0, 315.0),
 ('Gambia', 2705995, 12598.0, 372.0),
 ('Congo', 5970430, 25087.0, 388.0),
 ('Burkina Faso', 22673764, 22056.0, 396.0),
 ('Saint Lucia', 179872, 30004.0, 409.0),
 ('French Guiana', 304568, 98041.0, 413.0),
 ('Cape Verde', 593162, 63244.0, 413.0),
 ('Guam', 171783, 50869.0, 420.0),
 ('Guinea', 13859349, 38267.0, 467.0),
 ('Barbados', 281646, 106645.0, 575.0),
 ('French Polynesia', 306292, 78055.0, 649.0),
 ('Papua New Guinea', 10142625, 46825.0, 670.0),
 ('Qatar', 2695131, 494737.0, 688.0),
 ('Belize', 405285, 70757.0, 688.0),
 ('Lesotho', 2305826, 34490.0, 706.0),
 ('Mali', 22593598, 33051.0, 743.0),
 ('Laos', 7529477, 218020.0, 758.0),
 ('Malta', 533293, 117610.0, 828.0),
 ('Bahamas', 409989, 37491.0, 833.0),
 ("Cote d'Ivoire", 28160548, 88208.0, 834.0),
 ('Tanzania', 65497752, 42846.0, 846.0),
 ('Haiti', 11585003, 34202.0, 860.0),
 ('Fiji', 929769, 68897.0, 883.0),
 ('Reunion', 974062, 494595.0, 921.0),
 ('Mauritania', 4736146, 63439.0, 997.0),
 ('Guadeloupe', 395762, 201886.0, 1010.0),
 ('Mauritius', 1299478, 296042.0, 1044.0),
 ('Martinique', 367512, 229020.0, 1092.0),
 ('Luxembourg', 647601, 317367.0, 1220.0),
 ('Guyana', 808727, 73075.0, 1298.0),
 ('Cyprus', 896007, 650685.0, 1330.0),
 ('Somalia', 17597508, 27324.0, 1361.0),
 ('Suriname', 618046, 82467.0, 1404.0),
 ('Madagascar', 29611718, 67865.0, 1422.0),
 ('Eswatini', 1201680, 74199.0, 1423.0),
 ('Ghana', 33475870, 171172.0, 1462.0),
 ('Democratic Republic of Congo', 99010216, 95748.0, 1464.0),
 ('Rwanda', 13776702, 133172.0, 1468.0),
 ('Bahrain', 1472237, 696614.0, 1536.0),
 ('Uzbekistan', 34627648, 251247.0, 1637.0),
 ('Singapore', 5637022, 2230570.0, 1722.0),
 ('Angola', 35588996, 105277.0, 1933.0),
 ('Cameroon', 27914542, 124392.0, 1965.0),
 ('Senegal', 17316452, 88921.0, 1971.0),
 ('Mongolia', 3398373, 1007900.0, 2136.0),
 ('Yemen', 33696612, 11945.0, 2159.0),
 ('Mozambique', 32969520, 233214.0, 2242.0),
 ('United Arab Emirates', 9441138, 1052664.0, 2349.0),
 ('New Zealand', 5185289, 2176499.0, 2548.0),
 ('Kuwait', 4268886, 663860.0, 2570.0),
 ('Malawi', 20405318, 88605.0, 2686.0),
 ('Botswana', 2630300, 329758.0, 2795.0),
 ('Montenegro', 627082, 288622.0, 2805.0),
 ('Estonia', 1326064, 615433.0, 2940.0),
 ('Kyrgyzstan', 6630621, 206708.0, 2991.0),
 ('Cambodia', 16767851, 138719.0, 3056.0),
 ('Nigeria', 218541216, 266598.0, 3155.0),
 ('Syria', 22125242, 57423.0, 3163.0),
 ('Kosovo', 1782115, 273181.0, 3201.0),
 ('Jamaica', 2827382, 154287.0, 3511.0),
 ('Albania', 2842318, 333532.0, 3598.0),
 ('Uganda', 47249588, 170409.0, 3630.0),
 ('Zambia', 20017670, 342954.0, 4057.0),
 ('Namibia', 2567024, 171156.0, 4090.0),
 ('El Salvador', 6336393, 201785.0, 4230.0),
 ('Trinidad and Tobago', 1531043, 189296.0, 4347.0),
 ('Dominican Republic', 11228821, 660790.0, 4384.0),
 ('Oman', 4576300, 399449.0, 4628.0),
 ('Sudan', 46874200, 63829.0, 5017.0),
 ('Norway', 5434324, 1479333.0, 5213.0),
 ('Zimbabwe', 16320539, 264127.0, 5668.0),
 ('Kenya', 54027484, 342932.0, 5688.0),
 ('Palestine', 5250076, 703228.0, 5708.0),
 ('Puerto Rico', 3252412, 1100123.0, 5810.0),
 ('Venezuela', 28301700, 552125.0, 5854.0),
 ('Latvia', 1850654, 976162.0, 6269.0),
 ('Libya', 6812344, 507187.0, 6437.0),
 ('Algeria', 44903228, 271463.0, 6881.0),
 ('Belarus', 9534956, 994037.0, 7118.0),
 ('Ethiopia', 123379928, 500014.0, 7572.0),
 ('Uruguay', 3422796, 1034303.0, 7617.0),
 ('Afghanistan', 41128772, 209414.0, 7879.0),
 ('Denmark', 5882259, 3403958.0, 8284.0),
 ('Cuba', 11212198, 1112631.0, 8530.0),
 ('Panama', 4408582, 1031731.0, 8609.0),
 ('Ireland', 5023108, 1703850.0, 8691.0),
 ('Armenia', 2780472, 447308.0, 8727.0),
 ('Finland', 5540745, 1462976.0, 8936.0),
 ('Slovenia', 2119843, 1330654.0, 9150.0),
 ('Costa Rica', 5180836, 1209725.0, 9245.0),
 ('Lithuania', 2750058, 1307021.0, 9595.0),
 ('Saudi Arabia', 36408824, 829882.0, 9617.0),
 ('North Macedonia', 2093606, 346852.0, 9662.0),
 ('Azerbaijan', 10358078, 828730.0, 10129.0),
 ('Lebanon', 5489744, 1232517.0, 10840.0),
 ('Honduras', 10432858, 472219.0, 11111.0),
 ('Moldova', 3272993, 611050.0, 12003.0),
 ('Nepal', 30547586, 1001149.0, 12020.0),
 ('Israel', 9449000, 4801511.0, 12307.0),
 ('Switzerland', 8740471, 4391007.0, 13949.0),
 ('Jordan', 11285875, 1746997.0, 14122.0),
 ('Bosnia and Herzegovina', 3233530, 401729.0, 16280.0),
 ('Morocco', 37457976, 1272490.0, 16296.0),
 ('Sri Lanka', 21832150, 672034.0, 16830.0),
 ('Georgia', 3744385, 1827537.0, 16971.0),
 ('Serbia', 6871547, 2497248.0, 17864.0),
 ('Croatia', 4030361, 1269326.0, 17987.0),
 ('Kazakhstan', 19397998, 1499224.0, 19071.0),
 ('Australia', 26177410, 11380700.0, 19447.0),
 ('Myanmar', 54179312, 633947.0, 19490.0),
 ('Paraguay', 6780745, 735709.0, 19878.0),
 ('Guatemala', 17843914, 1237564.0, 20178.0),
 ('Slovakia', 5643455, 1863590.0, 21031.0),
 ('Austria', 8939617, 5943417.0, 21923.0),
 ('Bolivia', 12224114, 1193970.0, 22365.0),
 ('Netherlands', 17564020, 8598182.0, 22992.0),
 ('Sweden', 10549349, 2698535.0, 23731.0),
 ('Egypt', 110990096, 515759.0, 24812.0),
 ('Oceania', 45038860, 14043499.0, 25324.0),
 ('Iraq', 44496124, 2465545.0, 25375.0),
 ('Portugal', 10270857, 5570473.0, 26266.0),
 ('Tunisia', 12356116, 1150962.0, 29331.0),
 ('Bangladesh', 171186368, 2037871.0, 29445.0),
 ('Pakistan', 235824864, 1577213.0, 30643.0),
 ('Belgium', 11655923, 4727795.0, 33775.0),
 ('Thailand', 71697024, 4728182.0, 33918.0),
 ('South Korea', 51815808, 30581499.0, 34049.0),
 ('Ecuador', 18001002, 1057121.0, 36014.0),
 ('Greece', 10384972, 5896788.0, 36283.0),
 ('Malaysia', 33938216, 5043978.0, 36966.0),
 ('Bulgaria', 6781955, 1297243.0, 38219.0),
 ('Czechia', 10493990, 4615945.0, 42484.0),
 ('Vietnam', 98186856, 11526966.0, 43186.0),
 ('Low income', 737604900, 2286826.0, 47861.0),
 ('Hungary', 9967304, 2195926.0, 48651.0),
 ('Canada', 38454328, 4600615.0, 51447.0),
 ('Chile', 19603736, 5182360.0, 64247.0),
 ('Philippines', 115559008, 4077109.0, 66160.0),
 ('Romania', 19659270, 3346046.0, 67736.0),
 ('Japan', 123951696, 33264491.0, 72805.0),
 ('Turkey', 85341248, 17004677.0, 101419.0),
 ('South Africa', 59893884, 4061578.0, 102595.0),
 ('Ukraine', 39701744, 5399231.0, 111298.0),
 ('Poland', 39857144, 6437598.0, 118970.0),
 ('Spain', 47558632, 13770429.0, 119479.0),
 ('China', 1425887360, 99109603.0, 120227.0),
 ('Argentina', 45510324, 10044957.0, 130472.0),
 ('Colombia', 51874028, 6360089.0, 142629.0),
 ('Iran', 88550568, 7570743.0, 144902.0),
 ('Indonesia', 275501344, 6737606.0, 160934.0),
 ('France', 67813000, 38538948.0, 161397.0),
 ('Germany', 83369840, 38221663.0, 168583.0),
 ('Italy', 59037472, 25603510.0, 188322.0),
 ('United Kingdom', 67508936, 24396534.0, 207695.0),
 ('Peru', 34049588, 4486832.0, 219493.0),
 ('Africa', 1426736614, 13053883.0, 258748.0),
 ('Mexico', 127504120, 7470653.0, 333100.0),
 ('Russia', 144713312, 22363740.0, 396378.0),
 ('India', 1417173120, 44688367.0, 530775.0),
 ('Brazil', 215313504, 37076053.0, 699276.0),
 ('United States', 338289856, 102247392.0, 1111342.0),
 ('European Union', 450146793, 182481130.0, 1215072.0),
 ('Lower middle income', 3432097300, 96855618.0, 1338207.0),
 ('South America', 436816679, 67979025.0, 1350960.0),
 ('North America', 600323657, 122709749.0, 1583415.0),
 ('Asia', 4721383370, 294846415.0, 1624653.0),
 ('Europe', 744807803, 246769927.0, 2023316.0),
 ('Upper middle income', 2525921300, 242304899.0, 2649567.0),
 ('High income', 1250514600, 416752372.0, 2826859.0),
 ('World', 7975105024, 759407939.0, 6866421.0),
 ('England', 56550000, None, None),
 ('Taiwan', 23893396, None, None),
 ('Pitcairn', 47, 4.0, None),
 ('Northern Ireland', 1896000, None, None),
 ('Northern Cyprus', 382836, None, None),
 ('North Korea', 26069416, None, None),
 ('Vatican', 808, 26.0, None),
 ('Niue', 1952, 747.0, None),
 ('Wales', 3170000, None, None),
 ('Western Sahara', 576005, None, None),
 ('Scotland', 5466000, None, None),
 ('Macao', 695180, None, None),
 ('Falkland Islands', 3801, 1923.0, None),
 ('Turkmenistan', 6430777, None, None),
 ('Tokelau', 1893, 5.0, None),
 ('Tuvalu', 11335, 2779.0, None),
 ('Hong Kong', 7488863, None, None),
 ('Saint Helena', 5401, 2166.0, None)]

#### Ques 6: Get the death count by continent

In [50]:
%sql select continent, MAX(total_deaths) as totalDeaths from covid_deaths group by continent

 * postgresql://postgres:***@localhost/Covidanalysis
7 rows affected.

[('Africa', 102595.0),
 ('Asia', 530775.0),
 ('Europe', 396378.0),
 ('North America', 1111342.0),
 ('Oceania', 19447.0),
 ('South America', 699276.0),
 (None, 6866421.0)]

##### As in the above result, there is a none which is due to the null value in the continent column. We can get rid of it  follows:

In [54]:
%sql select continent, MAX(cast(total_deaths as int)) as totalDeaths from covid_deaths where continent is not null group by continent

 * postgresql://postgres:***@localhost/Covidanalysis
6 rows affected.

[('Africa', 102595),
 ('Asia', 530775),
 ('Europe', 396378),
 ('North America', 1111342),
 ('Oceania', 19447),
 ('South America', 699276)]

 #### Ques 7: Continent with the highest death count

In [58]:
%sql select continent, MAX(cast(total_deaths as int)) as totalDeaths from covid_deaths where continent is not null group by continent order by totalDeaths desc;

 * postgresql://postgres:***@localhost/Covidanalysis
6 rows affected.

[('North America', 1111342),
 ('South America', 699276),
 ('Asia', 530775),
 ('Europe', 396378),
 ('Africa', 102595),
 ('Oceania', 19447)]

#### Ques8: Get the deaths on everyday basis

In [61]:
%sql select date, cast(sum(new_deaths)as int) as newDeathsPerDay from covid_deaths group by date order by newDeathsPerDay

 * postgresql://postgres:***@localhost/Covidanalysis
1168 rows affected.

[(datetime.date(2020, 1, 11), 0),
 (datetime.date(2020, 1, 18), 0),
 (datetime.date(2020, 1, 15), 0),
 (datetime.date(2020, 1, 13), 0),
 (datetime.date(2020, 1, 14), 0),
 (datetime.date(2020, 1, 3), 0),
 (datetime.date(2020, 1, 10), 0),
 (datetime.date(2020, 1, 16), 0),
 (datetime.date(2020, 1, 5), 0),
 (datetime.date(2020, 1, 9), 0),
 (datetime.date(2020, 1, 6), 0),
 (datetime.date(2020, 1, 4), 0),
 (datetime.date(2020, 1, 7), 0),
 (datetime.date(2020, 1, 8), 0),
 (datetime.date(2020, 1, 20), 4),
 (datetime.date(2020, 1, 12), 4),
 (datetime.date(2020, 1, 17), 4),
 (datetime.date(2020, 1, 23), 4),
 (datetime.date(2020, 1, 19), 4),
 (datetime.date(2020, 2, 21), 5),
 (datetime.date(2020, 1, 29), 8),
 (datetime.date(2020, 1, 21), 8),
 (datetime.date(2020, 2, 12), 20),
 (datetime.date(2020, 2, 23), 22),
 (datetime.date(2020, 1, 24), 32),
 (datetime.date(2020, 1, 22), 44),
 (datetime.date(2020, 1, 26), 56),
 (datetime.date(2020, 1, 25), 64),
 (datetime.date(2020, 1, 27), 104),
 (datetime.date(2020, 1, 30), 152),
 (datetime.date(2020, 1, 31), 168),
 (datetime.date(2020, 2, 27), 171),
 (datetime.date(2020, 2, 1), 184),
 (datetime.date(2020, 3, 1), 192),
 (datetime.date(2020, 1, 28), 196),
 (datetime.date(2020, 2, 26), 251),
 (datetime.date(2020, 2, 28), 253),
 (datetime.date(2020, 2, 3), 256),
 (datetime.date(2020, 2, 4), 264),
 (datetime.date(2020, 2, 29), 264),
 (datetime.date(2020, 3, 2), 269),
 (datetime.date(2020, 2, 6), 280),
 (datetime.date(2020, 2, 5), 288),
 (datetime.date(2020, 2, 25), 320),
 (datetime.date(2020, 2, 7), 340),
 (datetime.date(2020, 3, 3), 343),
 (datetime.date(2020, 2, 8), 348),
 (datetime.date(2020, 2, 17), 392),
 (datetime.date(2020, 2, 11), 400),
 (datetime.date(2020, 2, 9), 400),
 (datetime.date(2020, 3, 4), 401),
 (datetime.date(2020, 3, 5), 403),
 (datetime.date(2020, 2, 2), 412),
 (datetime.date(2020, 2, 16), 416),
 (datetime.date(2020, 2, 10), 428),
 (datetime.date(2020, 2, 19), 452),
 (datetime.date(2020, 3, 6), 475),
 (datetime.date(2020, 2, 20), 500),
 (datetime.date(2020, 3, 7), 512),
 (datetime.date(2020, 2, 18), 556),
 (datetime.date(2020, 2, 15), 578),
 (datetime.date(2020, 3, 8), 582),
 (datetime.date(2020, 2, 14), 608),
 (datetime.date(2020, 2, 24), 633),
 (datetime.date(2020, 2, 22), 836),
 (datetime.date(2020, 3, 10), 986),
 (datetime.date(2020, 2, 13), 1012),
 (datetime.date(2020, 3, 9), 1056),
 (datetime.date(2023, 3, 7), 1108),
 (datetime.date(2023, 3, 6), 1133),
 (datetime.date(2020, 3, 11), 1408),
 (datetime.date(2020, 3, 12), 1713),
 (datetime.date(2020, 3, 13), 1803),
 (datetime.date(2023, 3, 5), 1878),
 (datetime.date(2023, 3, 1), 2002),
 (datetime.date(2023, 2, 26), 2116),
 (datetime.date(2020, 3, 15), 2173),
 (datetime.date(2023, 3, 3), 2271),
 (datetime.date(2023, 3, 2), 2278),
 (datetime.date(2023, 2, 28), 2303),
 (datetime.date(2023, 2, 22), 2323),
 (datetime.date(2020, 3, 14), 2365),
 (datetime.date(2023, 2, 19), 2459),
 (datetime.date(2023, 2, 21), 2587),
 (datetime.date(2023, 2, 23), 2630),
 (datetime.date(2023, 2, 27), 2738),
 (datetime.date(2023, 2, 14), 3039),
 (datetime.date(2023, 2, 13), 3061),
 (datetime.date(2023, 2, 16), 3204),
 (datetime.date(2023, 2, 15), 3211),
 (datetime.date(2023, 2, 8), 3234),
 (datetime.date(2023, 2, 12), 3250),
 (datetime.date(2023, 2, 9), 3330),
 (datetime.date(2022, 11, 21), 3491),
 (datetime.date(2020, 3, 16), 3536),
 (datetime.date(2023, 2, 7), 3583),
 (datetime.date(2023, 2, 6), 3584),
 (datetime.date(2020, 3, 17), 3673),
 (datetime.date(2023, 2, 18), 3675),
 (datetime.date(2022, 6, 6), 3705),
 (datetime.date(2023, 2, 24), 3734),
 (datetime.date(2022, 11, 13), 3740),
 (datetime.date(2022, 11, 28), 3746),
 (datetime.date(2022, 10, 17), 3753),
 (datetime.date(2022, 11, 6), 3787),
 (datetime.date(2022, 11, 14), 3794),
 (datetime.date(2022, 10, 23), 3842),
 (datetime.date(2023, 2, 11), 3916),
 (datetime.date(2023, 2, 5), 3953),
 (datetime.date(2022, 6, 14), 3974),
 (datetime.date(2022, 6, 7), 3977),
 (datetime.date(2022, 11, 20), 3980),
 (datetime.date(2022, 10, 10), 3991),
 (datetime.date(2022, 6, 13), 4034),
 (datetime.date(2022, 9, 26), 4041),
 (datetime.date(2022, 11, 27), 4074),
 (datetime.date(2022, 12, 4), 4118),
 (datetime.date(2022, 10, 30), 4123),
 (datetime.date(2023, 1, 29), 4136),
 (datetime.date(2023, 1, 31), 4146),
 (datetime.date(2022, 5, 31), 4150),
 (datetime.date(2022, 11, 17), 4177),
 (datetime.date(2023, 2, 20), 4180),
 (datetime.date(2022, 9, 20), 4244),
 (datetime.date(2022, 6, 20), 4275),
 (datetime.date(2023, 1, 30), 4291),
 (datetime.date(2020, 3, 18), 4294),
 (datetime.date(2022, 11, 7), 4317),
 (datetime.date(2022, 11, 24), 4322),
 (datetime.date(2022, 6, 28), 4388),
 (datetime.date(2022, 11, 10), 4421),
 (datetime.date(2022, 10, 31), 4422),
 (datetime.date(2023, 1, 25), 4510),
 (datetime.date(2022, 5, 23), 4542),
 (datetime.date(2023, 1, 26), 4555),
 (datetime.date(2022, 9, 13), 4561),
 (datetime.date(2023, 2, 4), 4562),
 (datetime.date(2022, 5, 30), 4597),
 (datetime.date(2022, 12, 5), 4608),
 (datetime.date(2022, 10, 24), 4655),
 (datetime.date(2022, 9, 19), 4669),
 (datetime.date(2022, 6, 1), 4736),
 (datetime.date(2023, 2, 1), 4741),
 (datetime.date(2022, 6, 27), 4745),
 (datetime.date(2022, 6, 21), 4757),
 (datetime.date(2022, 11, 3), 4815),
 (datetime.date(2022, 12, 11), 4829),
 (datetime.date(2022, 11, 9), 4900),
 (datetime.date(2022, 11, 16), 4970),
 (datetime.date(2022, 5, 24), 4982),
 (datetime.date(2022, 9, 12), 4990),
 (datetime.date(2022, 11, 30), 5058),
 (datetime.date(2022, 11, 15), 5069),
 (datetime.date(2022, 10, 3), 5070),
 (datetime.date(2022, 10, 27), 5075),
 (datetime.date(2022, 9, 25), 5124),
 (datetime.date(2022, 6, 22), 5168),
 (datetime.date(2022, 11, 8), 5171),
 (datetime.date(2022, 5, 17), 5174),
 (datetime.date(2022, 11, 23), 5180),
 (datetime.date(2022, 10, 2), 5186),
 (datetime.date(2023, 1, 28), 5206),
 (datetime.date(2022, 12, 12), 5210),
 (datetime.date(2022, 12, 1), 5227),
 (datetime.date(2022, 7, 4), 5279),
 (datetime.date(2020, 3, 19), 5311),
 (datetime.date(2022, 9, 28), 5344),
 (datetime.date(2022, 7, 5), 5368),
 (datetime.date(2022, 11, 22), 5381),
 (datetime.date(2022, 5, 16), 5386),
 (datetime.date(2022, 10, 4), 5387),
 (datetime.date(2022, 5, 10), 5406),
 (datetime.date(2022, 6, 15), 5438),
 (datetime.date(2022, 9, 21), 5444),
 (datetime.date(2023, 2, 2), 5465),
 (datetime.date(2022, 10, 16), 5519),
 (datetime.date(2022, 11, 29), 5541),
 (datetime.date(2022, 11, 12), 5607),
 (datetime.date(2022, 6, 11), 5610),
 (datetime.date(2022, 11, 1), 5647),
 (datetime.date(2022, 9, 18), 5651),
 (datetime.date(2022, 6, 8), 5665),
 (datetime.date(2022, 9, 6), 5690),
 (datetime.date(2022, 5, 9), 5736),
 (datetime.date(2022, 10, 21), 5774),
 (datetime.date(2022, 6, 4), 5795),
 (datetime.date(2022, 6, 19), 5803),
 (datetime.date(2022, 12, 6), 5841),
 (datetime.date(2022, 5, 21), 5870),
 (datetime.date(2022, 6, 5), 5896),
 (datetime.date(2022, 9, 27), 5923),
 (datetime.date(2022, 11, 19), 5966),
 (datetime.date(2022, 10, 29), 6007),
 (datetime.date(2022, 6, 16), 6013),
 (datetime.date(2022, 10, 26), 6043),
 (datetime.date(2020, 3, 20), 6055),
 (datetime.date(2022, 6, 12), 6072),
 (datetime.date(2022, 9, 14), 6089),
 (datetime.date(2022, 11, 5), 6091),
 (datetime.date(2022, 9, 7), 6137),
 (datetime.date(2022, 8, 16), 6150),
 (datetime.date(2022, 12, 7), 6178),
 (datetime.date(2022, 12, 8), 6215),
 (datetime.date(2022, 10, 9), 6228),
 (datetime.date(2022, 8, 30), 6303),
 (datetime.date(2022, 7, 11), 6316),
 (datetime.date(2022, 5, 28), 6356),
 (datetime.date(2022, 6, 2), 6380),
 (datetime.date(2022, 9, 29), 6388),
 (datetime.date(2022, 12, 3), 6412),
 (datetime.date(2022, 5, 25), 6428),
 (datetime.date(2022, 10, 25), 6440),
 (datetime.date(2022, 12, 15), 6446),
 (datetime.date(2022, 6, 29), 6513),
 (datetime.date(2022, 11, 26), 6536),
 (datetime.date(2022, 7, 6), 6545),
 (datetime.date(2022, 7, 12), 6605),
 (datetime.date(2022, 9, 22), 6611),
 (datetime.date(2022, 8, 23), 6632),
 (datetime.date(2022, 12, 18), 6703),
 (datetime.date(2022, 5, 22), 6747),
 (datetime.date(2022, 5, 29), 6758),
 (datetime.date(2022, 12, 19), 6767),
 (datetime.date(2022, 5, 15), 6812),
 (datetime.date(2022, 6, 3), 6830),
 (datetime.date(2022, 10, 5), 6872),
 (datetime.date(2022, 10, 18), 6908),
 (datetime.date(2022, 9, 23), 6931),
 (datetime.date(2022, 10, 12), 6942),
 (datetime.date(2022, 9, 11), 6992),
 (datetime.date(2022, 5, 3), 7017),
 (datetime.date(2022, 6, 26), 7054),
 (datetime.date(2022, 9, 5), 7084),
 (datetime.date(2022, 5, 18), 7137),
 (datetime.date(2022, 12, 10), 7150),
 (datetime.date(2022, 6, 17), 7195),
 (datetime.date(2022, 5, 11), 7219),
 (datetime.date(2022, 6, 23), 7220),
 (datetime.date(2022, 6, 9), 7267),
 (datetime.date(2022, 9, 15), 7287),
 (datetime.date(2022, 10, 11), 7308),
 (datetime.date(2022, 4, 25), 7339),
 (datetime.date(2022, 6, 24), 7360),
 (datetime.date(2022, 5, 14), 7380),
 (datetime.date(2022, 5, 2), 7394),
 (datetime.date(2022, 10, 6), 7405),
 (datetime.date(2020, 3, 21), 7423),
 (datetime.date(2022, 5, 20), 7428),
 (datetime.date(2022, 10, 13), 7441),
 (datetime.date(2022, 10, 1), 7450),
 (datetime.date(2022, 5, 27), 7468),
 (datetime.date(2022, 5, 4), 7495),
 (datetime.date(2022, 8, 9), 7516),
 (datetime.date(2022, 12, 14), 7522),
 (datetime.date(2022, 7, 3), 7539),
 (datetime.date(2022, 8, 29), 7562),
 (datetime.date(2022, 5, 26), 7655),
 (datetime.date(2022, 10, 20), 7664),
 (datetime.date(2022, 5, 8), 7707),
 (datetime.date(2022, 7, 1), 7718),
 (datetime.date(2022, 8, 22), 7727),
 (datetime.date(2022, 12, 13), 7777),
 (datetime.date(2022, 6, 30), 7777),
 (datetime.date(2022, 9, 8), 7822),
 (datetime.date(2022, 5, 19), 7847),
 (datetime.date(2022, 10, 14), 7863),
 (datetime.date(2022, 6, 18), 7885),
 (datetime.date(2022, 9, 9), 7901),
 (datetime.date(2022, 9, 16), 7981),
 (datetime.date(2022, 4, 19), 7983),
 (datetime.date(2022, 6, 10), 7986),
 (datetime.date(2022, 9, 4), 7998),
 (datetime.date(2022, 7, 18), 8053),
 (datetime.date(2022, 8, 15), 8088),
 (datetime.date(2022, 5, 7), 8138),
 (datetime.date(2022, 10, 19), 8154),
 (datetime.date(2022, 8, 1), 8212),
 (datetime.date(2022, 7, 19), 8223),
 (datetime.date(2022, 5, 13), 8231),
 (datetime.date(2022, 7, 10), 8253),
 (datetime.date(2022, 8, 2), 8264),
 (datetime.date(2022, 8, 31), 8349),
 (datetime.date(2022, 7, 7), 8441),
 (datetime.date(2022, 5, 12), 8444),
 (datetime.date(2022, 6, 25), 8467),
 (datetime.date(2022, 9, 10), 8490),
 (datetime.date(2022, 9, 17), 8497),
 (datetime.date(2022, 4, 30), 8593),
 (datetime.date(2022, 4, 18), 8658),
 (datetime.date(2022, 12, 21), 8728),
 (datetime.date(2023, 1, 23), 8747),
 (datetime.date(2022, 10, 7), 8752),
 (datetime.date(2023, 1, 24), 8877),
 (datetime.date(2022, 12, 25), 8893),
 (datetime.date(2022, 9, 24), 8904),
 (datetime.date(2022, 8, 8), 8911),
 (datetime.date(2022, 12, 17), 8928),
 (datetime.date(2022, 7, 26), 8938),
 (datetime.date(2022, 7, 13), 8946),
 (datetime.date(2022, 8, 24), 9025),
 (datetime.date(2022, 7, 24), 9040),
 (datetime.date(2022, 7, 2), 9101),
 (datetime.date(2022, 10, 8), 9103),
 (datetime.date(2020, 3, 23), 9169),
 (datetime.date(2022, 12, 22), 9187),
 (datetime.date(2022, 9, 30), 9210),
 (datetime.date(2022, 7, 17), 9268),
 (datetime.date(2022, 10, 15), 9316),
 (datetime.date(2022, 12, 26), 9381),
 (datetime.date(2020, 3, 22), 9427),
 (datetime.date(2023, 1, 22), 9442),
 (datetime.date(2022, 4, 27), 9443),
 (datetime.date(2022, 12, 20), 9468),
 (datetime.date(2022, 5, 6), 9482),
 (datetime.date(2022, 9, 2), 9486),
 (datetime.date(2022, 9, 1), 9517),
 (datetime.date(2022, 7, 8), 9520),
 (datetime.date(2022, 8, 28), 9575),
 (datetime.date(2022, 7, 20), 9621),
 (datetime.date(2022, 5, 1), 9659),
 (datetime.date(2022, 7, 9), 9743),
 (datetime.date(2022, 7, 25), 9775),
 (datetime.date(2022, 8, 17), 9857),
 (datetime.date(2022, 9, 3), 9887),
 (datetime.date(2022, 7, 14), 9902),
 (datetime.date(2022, 8, 10), 9985),
 (datetime.date(2022, 8, 25), 10026),
 (datetime.date(2022, 4, 24), 10060),
 (datetime.date(2020, 3, 24), 10083),
 (datetime.date(2022, 8, 21), 10145),
 (datetime.date(2022, 11, 2), 10145),
 (datetime.date(2022, 5, 5), 10206),
 (datetime.date(2022, 8, 27), 10224),
 (datetime.date(2022, 7, 15), 10494),
 (datetime.date(2022, 8, 3), 10568),
 (datetime.date(2022, 8, 26), 10687),
 (datetime.date(2022, 7, 27), 10711),
 (datetime.date(2022, 4, 11), 10720),
 (datetime.date(2022, 4, 12), 10857),
 (datetime.date(2022, 7, 16), 10876),
 (datetime.date(2022, 8, 19), 10952),
 (datetime.date(2022, 4, 4), 11030),
 (datetime.date(2022, 4, 28), 11089),
 (datetime.date(2022, 8, 7), 11143),
 (datetime.date(2022, 8, 12), 11151),
 (datetime.date(2022, 4, 23), 11186),
 (datetime.date(2022, 8, 18), 11300),
 (datetime.date(2022, 8, 4), 11354),
 (datetime.date(2022, 4, 17), 11357),
 (datetime.date(2022, 7, 31), 11360),
 (datetime.date(2022, 8, 14), 11431),
 (datetime.date(2022, 4, 20), 11470),
 (datetime.date(2022, 7, 28), 11486),
 (datetime.date(2023, 1, 19), 11534),
 (datetime.date(2022, 7, 29), 11676),
 (datetime.date(2022, 8, 5), 11741),
 (datetime.date(2022, 7, 21), 11822),
 (datetime.date(2023, 3, 4), 11831),
 (datetime.date(2022, 4, 29), 11862),
 (datetime.date(2022, 8, 20), 11876),
 (datetime.date(2023, 1, 18), 12023),
 (datetime.date(2022, 7, 22), 12028),
 (datetime.date(2022, 4, 16), 12141),
 (datetime.date(2022, 8, 11), 12161),
 (datetime.date(2022, 4, 21), 12197),
 (datetime.date(2022, 7, 23), 12308),
 (datetime.date(2022, 4, 13), 12367),
 (datetime.date(2022, 12, 2), 12408),
 (datetime.date(2022, 12, 29), 12460),
 (datetime.date(2022, 12, 24), 12477),
 (datetime.date(2022, 8, 6), 12650),
 (datetime.date(2020, 3, 25), 12688),
 (datetime.date(2022, 11, 18), 12878),
 (datetime.date(2022, 12, 27), 12898),
 (datetime.date(2022, 4, 5), 12931),
 (datetime.date(2023, 1, 21), 13106),
 (datetime.date(2023, 1, 17), 13115),
 (datetime.date(2022, 7, 30), 13151),
 (datetime.date(2022, 11, 11), 13187),
 (datetime.date(2023, 1, 15), 13309),
 (datetime.date(2022, 4, 22), 13314),
 (datetime.date(2022, 3, 28), 13362),
 (datetime.date(2022, 4, 15), 13465),
 (datetime.date(2020, 3, 26), 13490),
 (datetime.date(2022, 8, 13), 13575),
 (datetime.date(2022, 4, 26), 14045),
 (datetime.date(2022, 12, 28), 14140),
 (datetime.date(2022, 11, 4), 14166),
 (datetime.date(2022, 3, 29), 14344),
 (datetime.date(2022, 4, 10), 14391),
 (datetime.date(2022, 4, 9), 14464),
 (datetime.date(2022, 4, 3), 14530),
 (datetime.date(2022, 4, 6), 14531),
 (datetime.date(2022, 11, 25), 14818),
 (datetime.date(2022, 10, 22), 15142),
 (datetime.date(2022, 4, 14), 15251),
 (datetime.date(2022, 4, 7), 15303),
 (datetime.date(2023, 2, 17), 15413),
 (datetime.date(2023, 2, 25), 15476),
 (datetime.date(2020, 3, 27), 15620),
 (datetime.date(2023, 1, 16), 15998),
 (datetime.date(2022, 3, 27), 16656),
 (datetime.date(2020, 6, 23), 16728),
 (datetime.date(2020, 6, 9), 16795),
 (datetime.date(2020, 5, 26), 16951),
 (datetime.date(2023, 1, 1), 17012),
 (datetime.date(2022, 4, 2), 17071),
 (datetime.date(2020, 5, 19), 17089),
 (datetime.date(2020, 6, 2), 17102),
 (datetime.date(2022, 3, 21), 17268),
 (datetime.date(2022, 4, 8), 17374),
 (datetime.date(2023, 1, 14), 17438),
 (datetime.date(2020, 6, 24), 17443),
 (datetime.date(2020, 5, 25), 17490),
 (datetime.date(2020, 3, 30), 17577),
 (datetime.date(2022, 12, 31), 17628),
 (datetime.date(2020, 5, 27), 17696),
 (datetime.date(2020, 6, 3), 17786),
 (datetime.date(2020, 3, 28), 17792),
 (datetime.date(2022, 10, 28), 17914),
 (datetime.date(2020, 6, 16), 17948),
 (datetime.date(2022, 12, 9), 18072),
 (datetime.date(2020, 6, 30), 18192),
 (datetime.date(2022, 1, 3), 18269),
 (datetime.date(2020, 5, 20), 18567),
 (datetime.date(2022, 12, 16), 18672),
 (datetime.date(2020, 3, 29), 18729),
 (datetime.date(2022, 3, 31), 18812),
 (datetime.date(2020, 5, 12), 18889),
 (datetime.date(2020, 6, 1), 18897),
 (datetime.date(2023, 1, 12), 18905),
 (datetime.date(2021, 12, 27), 18926),
 (datetime.date(2020, 6, 10), 18974),
 (datetime.date(2023, 1, 8), 18990),
 (datetime.date(2022, 3, 16), 19048),
 (datetime.date(2020, 5, 28), 19104),
 (datetime.date(2020, 9, 22), 19132),
 (datetime.date(2020, 6, 15), 19146),
 (datetime.date(2020, 7, 7), 19163),
 (datetime.date(2020, 9, 29), 19186),
 (datetime.date(2022, 3, 15), 19398),
 (datetime.date(2022, 3, 14), 19429),
 (datetime.date(2022, 3, 30), 19455),
 (datetime.date(2020, 9, 9), 19455),
 (datetime.date(2020, 5, 18), 19489),
 (datetime.date(2020, 5, 13), 19506),
 (datetime.date(2022, 3, 23), 19575),
 (datetime.date(2020, 6, 14), 19727),
 (datetime.date(2020, 7, 1), 19746),
 (datetime.date(2020, 6, 29), 19824),
 (datetime.date(2020, 9, 1), 19837),
 (datetime.date(2022, 4, 1), 19935),
 (datetime.date(2020, 6, 7), 20003),
 (datetime.date(2023, 1, 11), 20039),
 (datetime.date(2020, 10, 6), 20046),
 (datetime.date(2020, 9, 30), 20103),
 (datetime.date(2022, 3, 20), 20148),
 (datetime.date(2020, 5, 31), 20162),
 (datetime.date(2020, 6, 8), 20191),
 (datetime.date(2020, 10, 14), 20235),
 (datetime.date(2020, 10, 12), 20240),
 (datetime.date(2020, 6, 22), 20259),
 (datetime.date(2020, 10, 7), 20284),
 (datetime.date(2020, 9, 16), 20382),
 (datetime.date(2020, 10, 13), 20385),
 (datetime.date(2020, 10, 5), 20393),
 (datetime.date(2020, 9, 23), 20425),
 (datetime.date(2020, 6, 28), 20435),
 (datetime.date(2020, 5, 5), 20491),
 (datetime.date(2020, 7, 8), 20506),
 (datetime.date(2022, 1, 2), 20581),
 (datetime.date(2020, 3, 31), 20614),
 (datetime.date(2020, 5, 23), 20683),
 (datetime.date(2023, 2, 10), 20688),
 (datetime.date(2022, 1, 10), 20741),
 (datetime.date(2020, 9, 10), 20769),
 (datetime.date(2020, 7, 14), 20827),
 (datetime.date(2023, 1, 9), 20849),
 (datetime.date(2021, 12, 20), 20865),
 (datetime.date(2020, 5, 22), 20870),
 (datetime.date(2022, 1, 4), 20899),
 (datetime.date(2020, 7, 6), 20934),
 (datetime.date(2020, 5, 4), 20992),
 (datetime.date(2020, 5, 6), 21022),
 (datetime.date(2020, 9, 15), 21042),
 (datetime.date(2020, 9, 21), 21104),
 (datetime.date(2020, 6, 21), 21124),
 (datetime.date(2020, 6, 26), 21150),
 (datetime.date(2020, 5, 29), 21158),
 (datetime.date(2020, 9, 2), 21170),
 (datetime.date(2023, 1, 2), 21230),
 (datetime.date(2020, 7, 2), 21268),
 (datetime.date(2020, 9, 28), 21405),
 (datetime.date(2020, 8, 25), 21460),
 (datetime.date(2020, 10, 15), 21500),
 (datetime.date(2020, 5, 10), 21538),
 (datetime.date(2020, 5, 21), 21544),
 (datetime.date(2020, 7, 3), 21558),
 (datetime.date(2020, 5, 11), 21588),
 (datetime.date(2020, 10, 11), 21658),
 (datetime.date(2020, 7, 15), 21672),
 (datetime.date(2020, 6, 11), 21708),
 (datetime.date(2020, 6, 4), 21739),
 (datetime.date(2020, 5, 14), 21743),
 (datetime.date(2020, 9, 14), 21752),
 (datetime.date(2022, 3, 7), 21809),
 (datetime.date(2020, 10, 4), 21836),
 (datetime.date(2021, 12, 28), 21837),
 (datetime.date(2020, 10, 19), 21849),
 (datetime.date(2022, 12, 23), 21865),
 (datetime.date(2020, 9, 27), 21913),
 (datetime.date(2020, 5, 30), 21933),
 (datetime.date(2022, 3, 24), 21961),
 (datetime.date(2020, 5, 17), 22002),
 (datetime.date(2020, 9, 20), 22025),
 (datetime.date(2021, 12, 26), 22041),
 (datetime.date(2020, 8, 26), 22072),
 (datetime.date(2020, 9, 13), 22132),
 (datetime.date(2020, 6, 13), 22133),
 (datetime.date(2020, 10, 20), 22149),
 (datetime.date(2020, 8, 18), 22195),
 (datetime.date(2020, 5, 24), 22221),
 (datetime.date(2020, 6, 5), 22222),
 (datetime.date(2020, 10, 3), 22231),
 (datetime.date(2020, 6, 12), 22253),
 (datetime.date(2020, 5, 15), 22254),
 (datetime.date(2020, 7, 4), 22411),
 (datetime.date(2020, 6, 18), 22412),
 (datetime.date(2020, 6, 20), 22448),
 (datetime.date(2020, 7, 28), 22456),
 (datetime.date(2020, 7, 21), 22513),
 (datetime.date(2020, 8, 12), 22545),
 (datetime.date(2023, 1, 7), 22599),
 (datetime.date(2023, 1, 10), 22623),
 (datetime.date(2020, 4, 28), 22643),
 (datetime.date(2020, 9, 6), 22663),
 (datetime.date(2020, 4, 27), 22669),
 (datetime.date(2022, 3, 19), 22670),
 (datetime.date(2020, 6, 25), 22676),